import { db } from './db';
import type { Question } from './types';

const seedQuestions: Question[] = [
  // 电子技术 - 模电
  { id: 'elec-1', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '在共射放大电路中，输出电压与输入电压的相位关系是？', options: ['同相', '反相', '相差90°', '相差180°'],
    answer: 'B', analysis: '共射放大电路输出与输入反相，这是共射电路的基本特性。共集（射随器）为同相，共基也为同相。',
    difficulty: 'easy', tags: ['BJT', '共射放大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-2', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: 'BJT处于放大区时，发射结和集电结的偏置状态分别是？', options: ['正偏/正偏', '正偏/反偏', '反偏/正偏', '反偏/反偏'],
    answer: 'B', analysis: '放大区：发射结正偏，集电结反偏。饱和区两者都正偏，截止区两者都反偏。',
    difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-3', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放两输入端"虚短"成立的条件是？', options: ['开环', '正反馈', '负反馈深度足够', '电源电压足够大'],
    answer: 'C', analysis: '虚短是负反馈深度足够时的近似。开环时虚短不成立（比较器工作状态）。虚断由输入电阻无穷大保证，任何条件下基本成立。',
    difficulty: 'medium', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-4', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '用卡诺图化简逻辑函数 F(A,B,C,D)=Σm(0,2,5,7,8,10,13,15) 的最简与或式为？', options: ['BD+B\'D\'', 'BD+AC', 'B\'D+BD\'', 'A\'C\'+AC'],
    answer: 'A', analysis: '四变量卡诺图，将最小项填入后圈1合并：m0(0000)、m2(0010)、m8(1000)、m10(1010) → B\'D\'；m5(0101)、m7(0111)、m13(1101)、m15(1111) → BD。',
    difficulty: 'hard', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-28' },

  // 高数
  { id: 'math-1', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (sin 3x) / x = ?', options: ['1', '3', '1/3', '0'],
    answer: 'B', analysis: 'lim(x→0) sin(ax)/x = a。原式 = lim(x→0) (sin 3x)/(3x) × 3 = 1 × 3 = 3。等价无穷小 sin 3x ~ 3x (x→0) 直接得出。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-2', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y = x²·eˣ 的导数 y\' = ?', options: ['2x·eˣ', 'x²·eˣ', 'xeˣ(x+2)', '2xeˣ + eˣ'],
    answer: 'C', analysis: '乘积求导：(uv)\' = u\'v + uv\'。u=x², u\'=2x；v=eˣ, v\'=eˣ。y\'=2xeˣ + x²eˣ = xeˣ(2+x) = xeˣ(x+2)。',
    difficulty: 'easy', tags: ['求导', '乘积法则'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-3', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '∫ x·cos(x²) dx = ?', options: ['sin(x²) + C', '½sin(x²) + C', 'cos(x²) + C', '½cos(x²) + C'],
    answer: 'B', analysis: '凑微分：令 u=x²，du=2xdx，xdx=du/2。∫ xcos(x²)dx = ½∫ cos u du = ½sin u + C = ½sin(x²) + C。',
    difficulty: 'medium', tags: ['积分', '凑微分'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-4', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '曲线 y = x³ - 3x 的拐点坐标是？', options: ['(0, 0)', '(1, -2)', '(-1, 2)', '(0, 0)和(±1, ∓2)'],
    answer: 'A', analysis: 'y\'=3x²-3, y\'\'=6x。令 y\'\'=0 得 x=0。x<0 时 y\'\'<0（凸），x>0 时 y\'\'>0（凹）。拐点为 (0,0)。',
    difficulty: 'medium', tags: ['拐点', '二阶导数'], source: 'manual', createdAt: '2026-07-28' },

  // 英语
  { id: 'eng-1', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I ___ you, I would accept the offer.', options: ['am', 'was', 'were', 'be'],
    answer: 'C', analysis: '虚拟语气，与现在事实相反，if 从句用过去式，be 动词一律用 were。',
    difficulty: 'easy', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-2', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The book ___ on the desk is mine.', options: ['lying', 'laying', 'lied', 'lay'],
    answer: 'A', analysis: 'lie(躺/位于)的现在分词是 lying。lay(放置)是及物动词。后置定语用现在分词。',
    difficulty: 'medium', tags: ['非谓语动词', '分词'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-3', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: 'The word "inevitable" most nearly means:', options: ['avoidable', 'certain to happen', 'impossible', 'desirable'],
    answer: 'B', analysis: 'inevitable = unavoidable, certain to happen（不可避免的，必然发生的）。前缀 in-(不) + evitable(可避免的)。',
    difficulty: 'easy', tags: ['词汇'], source: 'manual', createdAt: '2026-07-28' },

  // 政治
  { id: 'pol-1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '唯物辩证法的实质和核心是？', options: ['质量互变规律', '否定之否定规律', '对立统一规律', '原因和结果'],
    answer: 'C', analysis: '对立统一规律（矛盾规律）揭示了事物发展的源泉和动力，是唯物辩证法的实质和核心。',
    difficulty: 'easy', tags: ['辩证法', '矛盾'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-2', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '中国式现代化的本质要求中，第一位的是？', options: ['实现高质量发展', '坚持中国共产党领导', '发展全过程人民民主', '实现全体人民共同富裕'],
    answer: 'B', analysis: '党的二十大报告明确指出：中国式现代化的本质要求是坚持中国共产党领导，坚持中国特色社会主义。党的领导是第一位的。',
    difficulty: 'easy', tags: ['中国式现代化', '二十大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-3', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'single',
    stem: '毛泽东思想"活的灵魂"不包括以下哪一项？', options: ['实事求是', '群众路线', '独立自主', '武装斗争'],
    answer: 'D', analysis: '毛泽东思想活的灵魂是实事求是、群众路线、独立自主三个方面。武装斗争是"三大法宝"之一（统一战线、武装斗争、党的建设），不是活的灵魂。',
    difficulty: 'medium', tags: ['毛泽东思想', '活的灵魂'], source: 'manual', createdAt: '2026-07-28' },

  // ===== 电子技术补充（模电/数电，真题风格）=====
  { id: 'elec-5', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '共集电极放大电路（射极跟随器）的电压放大倍数约为？', options: ['远大于1', '等于0', '接近1且略小于1', '小于0且绝对值很大'],
    answer: 'C', analysis: '射极跟随器电压增益略小于1，输入电阻大、输出电阻小，常用于缓冲和阻抗变换。',
    difficulty: 'easy', tags: ['BJT', '共集电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-6', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '分压偏置式共射放大电路稳定静态工作点主要依靠？', options: ['增大电源电压', '减小基极电阻Rb', '提高环境温度', 'Re的直流负反馈'],
    answer: 'D', analysis: '发射极电阻Re引入直流负反馈：温度升高→Ic增大→Ie增大→Ue升高→UBE减小→IB减小→Ic回落，从而稳定工作点。',
    difficulty: 'medium', tags: ['BJT', '静态工作点'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-7', subject: 'electronics', chapter: '反馈放大电路', type: 'single',
    stem: '电压串联负反馈对放大电路的影响是？', options: ['稳定输出电流、减小输入电阻', '稳定输出电压、减小输入电阻', '稳定输出电流、增大输入电阻', '稳定输出电压、增大输入电阻'],
    answer: 'D', analysis: '电压负反馈稳定输出电压，串联负反馈增大输入电阻。四种组合：电压/电流×串联/并联，效果各不相同，是高频考点。',
    difficulty: 'medium', tags: ['负反馈'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-8', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放"虚断"成立的依据是？', options: ['开环电压增益无穷大', '输出电阻为零', '通频带无限宽', '输入电阻无穷大'],
    answer: 'D', analysis: '虚断因理想运放输入电阻无穷大，流入输入端电流近似为0。虚短则由开环增益无穷大加负反馈保证。',
    difficulty: 'easy', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-9', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '反相比例运算电路 Rf=100kΩ、R1=10kΩ，电压增益为？', options: ['10', '-11', '11', '-10'],
    answer: 'D', analysis: '反相比例：Av = -Rf/R1 = -100/10 = -10。注意反相放大器增益为负，且可小于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-10', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '同相比例运算电路 Rf=90kΩ、R1=10kΩ，电压增益为？', options: ['9', '10', '-9', '11'],
    answer: 'B', analysis: '同相比例：Av = 1 + Rf/R1 = 1 + 90/10 = 10。同相比例增益恒大于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-11', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '逻辑函数 F=(A·B)\' 用摩根定律展开为？', options: ["A'·B'", "A'+B'", 'A+B', "A·B'"],
    answer: 'B', analysis: '摩根定律：(A·B)\' = A\'+B\'，(A+B)\' = A\'·B\'。与变或、或变与、变量取反，常与卡诺图化简配合考查。',
    difficulty: 'easy', tags: ['摩根定律', '逻辑代数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-12', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '卡诺图中两个相邻最小项合并后可以消去？', options: ['2个变量', '3个变量', '不能消去变量', '1个变量'],
    answer: 'D', analysis: '2^n个相邻最小项合并可消去n个变量。两个相邻格（2¹个）消去1个变量，四个相邻格消去2个变量。',
    difficulty: 'medium', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-13', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'JK触发器在 J=1、K=1 时，CP 到来后触发器的状态为？', options: ['保持原态', '置1', '翻转', '置0'],
    answer: 'C', analysis: 'J=1、K=1 时 JK触发器每来一个CP翻转一次（T触发器功能）。J=K=0保持，J=1、K=0置1，J=0、K=1置0。',
    difficulty: 'medium', tags: ['JK触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-14', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'D触发器在 CP 有效沿到来后，Q 的状态为？', options: ['Q=D', 'Q=Q\'', 'Q=0', 'Q保持不变'],
    answer: 'A', analysis: 'D触发器特性方程 Q(n+1)=D。输出跟随输入，常用于数据寄存和分频。',
    difficulty: 'easy', tags: ['D触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-15', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: '由4个触发器构成的二进制异步计数器最多可有多少种状态？', options: ['8种', '16种', '4种', '32种'],
    answer: 'B', analysis: 'n个触发器构成模2^n计数器。4个触发器最多2^4=16种状态，即模16计数器。',
    difficulty: 'easy', tags: ['计数器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-16', subject: 'electronics', chapter: '直流稳压电源', type: 'single',
    stem: '桥式整流电路（无滤波）输出的直流电压平均值约为副边电压有效值的？', options: ['0.9倍', '0.45倍', '1.2倍', '1.41倍'],
    answer: 'A', analysis: '桥式整流为全波整流，Uo≈0.9U2；半波整流0.45U2；电容滤波后约1.2U2；峰值1.41U2。四个数字是高频考点。',
    difficulty: 'medium', tags: ['整流', '直流电源'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 高数补充 =====
  { id: 'math-5', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (eˣ-1)/x = ?', options: ['1', '0', 'e', '∞'],
    answer: 'A', analysis: '等价无穷小：x→0 时 eˣ-1 ~ x，故原式=1。常用的还有 ln(1+x)~x、1-cos x~x²/2。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-6', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '隐函数 x²+y²=25 在点 (3,4) 处的切线斜率为？', options: ['3/4', '-4/3', '4/3', '-3/4'],
    answer: 'D', analysis: '两边对x求导：2x+2y·y\'=0 → y\'=-x/y。代入(3,4)得 y\'=-3/4。',
    difficulty: 'medium', tags: ['隐函数求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-7', subject: 'math', chapter: '定积分及其应用', type: 'single',
    stem: '定积分 ∫₀¹ x² dx = ?', options: ['1/2', '1/3', '1', '2/3'],
    answer: 'B', analysis: '∫x²dx = x³/3，代入上下限：1/3 - 0 = 1/3。',
    difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-8', subject: 'math', chapter: '定积分及其应用', type: 'single',
    stem: '变上限积分求导：d/dx ∫₀ˣ sin t dt = ?', options: ['sin x', 'cos x', '-cos x', 'x·sin x'],
    answer: 'A', analysis: '微积分基本定理：d/dx ∫ₐˣ f(t)dt = f(x)。代入得 sin x。',
    difficulty: 'easy', tags: ['变上限积分', '求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-9', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '微分方程 y\'+y=0 的通解为？', options: ['y=Ceˣ', 'y=Ce⁻ˣ', 'y=Cx', 'y=C+ln x'],
    answer: 'B', analysis: '一阶线性齐次微分方程，特征方程 r+1=0 → r=-1，通解 y=Ce⁻ˣ。',
    difficulty: 'medium', tags: ['微分方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-10', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: '幂级数 Σ(n=1→∞) xⁿ/n 的收敛半径为？', options: ['1', '0', '∞', '2'],
    answer: 'A', analysis: '比值法：lim|a(n+1)/a(n)| = lim n/(n+1) = 1，收敛半径 R=1/1=1。',
    difficulty: 'medium', tags: ['幂级数', '收敛半径'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-11', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: 'x→0 时，1-cos x 与下列哪个是等价无穷小？', options: ['x²', 'x', 'x³/3', 'x²/2'],
    answer: 'C', analysis: '1-cos x ~ x²/2 (x→0)。由 1-cos x = 2sin²(x/2) 且 sin(x/2)~x/2 推出。',
    difficulty: 'medium', tags: ['等价无穷小', '极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-12', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '设 z=x²y，则 ∂z/∂x = ?', options: ['x²', '2xy', '2x+y', 'xy²'],
    answer: 'B', analysis: '对x求偏导时把y看作常数：∂(x²y)/∂x = 2xy。',
    difficulty: 'easy', tags: ['偏导数', '多元函数'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 英语补充 =====
  { id: 'eng-4', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I had studied harder, I ___ the exam.', options: ['will pass', 'would pass', 'had passed', 'would have passed'],
    answer: 'C', analysis: '与过去事实相反的虚拟语气：if 从句用 had done，主句用 would have done。',
    difficulty: 'medium', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-5', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The number of students in our class ___ 45.', options: ['are', 'is', 'were', 'have been'],
    answer: 'B', analysis: '"the number of + 复数名词"作主语，谓语用单数。"a number of"才是复数谓语。',
    difficulty: 'medium', tags: ['主谓一致'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-6', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He has lived in Beijing ___ 2019.', options: ['since', 'for', 'in', 'at'],
    answer: 'A', analysis: '现在完成时接时间点用 since（since 2019），接时间段用 for（for five years）。',
    difficulty: 'easy', tags: ['时态', '完成时'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-7', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "postpone" 最接近的意思是？', options: ['give up', 'carry on', 'take over', 'put off'],
    answer: 'D', analysis: 'postpone = put off（推迟）。give up放弃、carry on继续、take over接管。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-8', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The man ___ is standing there is our teacher.', options: ['whom', 'who', 'whose', 'which'],
    answer: 'B', analysis: '先行词 the man 在从句中作主语，用 who。whom 作宾语，which 指物，whose 表所有。',
    difficulty: 'easy', tags: ['定语从句'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 政治补充 =====
  { id: 'pol-4', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '"世界的本原是物质"这一观点属于？', options: ['唯心主义一元论', '二元论', '不可知论', '唯物主义一元论'],
    answer: 'D', analysis: '承认世界本原只有一个且是物质，是唯物主义一元论。二元论认为有两个本原，不可知论否认世界可知性。',
    difficulty: 'easy', tags: ['唯物论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-5', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '新民主主义革命的领导阶级是？', options: ['资产阶级', '无产阶级', '农民阶级', '小资产阶级'],
    answer: 'B', analysis: '新民主主义革命是无产阶级领导的。领导权问题是革命成败的关键，这是与旧民主主义革命的根本区别。',
    difficulty: 'easy', tags: ['新民主主义革命'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-6', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '新时代我国社会主要矛盾是？', options: ['人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾', '人民日益增长的物质文化需要同落后的社会生产之间的矛盾', '生产力和生产关系之间的矛盾', '经济基础和上层建筑之间的矛盾'],
    answer: 'A', analysis: '党的十九大提出：新时代主要矛盾是人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。选项B是旧表述。',
    difficulty: 'medium', tags: ['主要矛盾', '新时代'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-7', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '下列不属于"四个自信"的是？', options: ['道路自信', '理论自信', '经济自信', '文化自信'],
    answer: 'C', analysis: '四个自信：道路自信、理论自信、制度自信、文化自信。没有"经济自信"。',
    difficulty: 'easy', tags: ['四个自信'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-8', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '检验认识真理性的唯一标准是？', options: ['逻辑证明', '权威意见', '多数人认同', '实践'],
    answer: 'D', analysis: '实践是检验真理的唯一标准。逻辑证明是重要补充但不是最终标准。',
    difficulty: 'easy', tags: ['认识论'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 电子技术扩充二（elec-17..40，共 24 题）=====
  { id: 'elec-17', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: 'BJT 发射结和集电结都正偏时，三极管工作在？', options: ['放大区', '饱和区', '截止区', '击穿区'],
    answer: 'B', analysis: '两个结都正偏为饱和区；发射结正偏集电结反偏为放大区；两个都反偏为截止区。',
    difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-18', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '共射放大电路中增大集电极电阻 Rc，电压增益将？', options: ['减小', '不变', '增大', '变为零'],
    answer: 'C', analysis: '共射增益 Au≈-βRc/rbe，Rc 增大增益增大；但 Rc 过大会使静态工作点进入饱和区。',
    difficulty: 'medium', tags: ['BJT', '共射放大'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-19', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '静态工作点设置过低（IB 偏小）时，输出波形容易出现？', options: ['饱和失真', '交越失真', '截止失真', '电源纹波失真'],
    answer: 'C', analysis: '工作点过低靠近截止区，信号负半周被削顶，产生截止失真；过高则产生饱和失真。',
    difficulty: 'medium', tags: ['BJT', '失真'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-20', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '环境温度升高时，BJT 的集电极电流 Icbo 和 Ic 将？', options: ['减小', '不变', '增大', '先增后减'],
    answer: 'C', analysis: '温度升高→少数载流子增多→Icbo 增大→Ic 增大，这是温漂的主要原因，常用分压偏置抑制。',
    difficulty: 'easy', tags: ['BJT', '温度特性'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-21', subject: 'electronics', chapter: '多级放大电路', type: 'single',
    stem: '能放大直流信号的级间耦合方式是？', options: ['阻容耦合', '变压器耦合', '直接耦合', '光电耦合'],
    answer: 'C', analysis: '阻容耦合和变压器耦合的电容/变压器隔直流，只能传交流；直接耦合可传直流信号，但存在零点漂移问题。',
    difficulty: 'medium', tags: ['多级放大', '耦合'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-22', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '射极跟随器（共集电路）的输出电阻特点是？', options: ['很大', '等于Re', '很小', '等于Rc'],
    answer: 'C', analysis: '共集电路输出电阻小、输入电阻大、电压增益≈1，常作缓冲级。',
    difficulty: 'easy', tags: ['共集电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-23', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '差分放大电路的主要作用是抑制？', options: ['差模信号', '共模信号', '高频信号', '低频信号'],
    answer: 'B', analysis: '差分电路利用对称结构抑制共模信号（温漂、电源干扰等），放大差模信号，是运放输入级。',
    difficulty: 'medium', tags: ['差分放大', '运放'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-24', subject: 'electronics', chapter: '功率放大电路', type: 'single',
    stem: '乙类互补对称功率放大器的理想最大效率为？', options: ['50%', '85%', '100%', '78.5%'],
    answer: 'D', analysis: '乙类理想效率 π/4≈78.5%；甲类最大 50%。乙类实际因交越失真需偏置，效率略低于 78.5%。',
    difficulty: 'medium', tags: ['功放', '效率'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-25', subject: 'electronics', chapter: '功率放大电路', type: 'single',
    stem: '乙类互补功放产生交越失真的原因是？', options: ['三极管存在死区电压', '电源电压不足', '负载电阻过小', '信号频率过高'],
    answer: 'A', analysis: '输入信号小于死区电压（约 0.5V）时三极管不导通，输出在过零处出现交越失真，常用甲乙类偏置消除。',
    difficulty: 'medium', tags: ['功放', '交越失真'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-26', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '用运放构成电压比较器时，运放工作在？', options: ['开环状态', '深度负反馈', '正反馈', '深度正反馈'],
    answer: 'A', analysis: '比较器工作在开环（或正反馈滞回）状态，利用开环增益无穷大使输出快速饱和到±Uom。',
    difficulty: 'easy', tags: ['运放', '比较器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-27', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '反相加法电路 R1=R2=Rf=10kΩ，两输入均为 1V 时输出电压为？', options: ['-2V', '2V', '-1V', '0V'],
    answer: 'A', analysis: '反相加法器 Uo=-Rf(U1/R1+U2/R2)=-10×(1/10+1/10)=-2V。',
    difficulty: 'medium', tags: ['运放', '加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-28', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '积分运算电路输入方波时，输出波形为？', options: ['三角波', '方波', '正弦波', '矩形波'],
    answer: 'A', analysis: '积分电路对输入求积分：方波积分得三角波；正弦波积分得余弦波。',
    difficulty: 'medium', tags: ['运放', '积分电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-29', subject: 'electronics', chapter: '反馈放大电路', type: 'single',
    stem: '电流并联负反馈对放大电路的影响是？', options: ['稳定输出电压、增大输入电阻', '稳定输出电压、减小输入电阻', '稳定输出电流、增大输入电阻', '稳定输出电流、减小输入电阻'],
    answer: 'D', analysis: '电流负反馈稳定输出电流，并联负反馈减小输入电阻。串/并联决定输入电阻增减，电压/电流决定稳定对象。',
    difficulty: 'hard', tags: ['负反馈'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-30', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '十进制数 13 对应的二进制数是？', options: ['1011', '1101', '1110', '1001'],
    answer: 'B', analysis: '13=8+4+1=1101₂。除 2 取余法或按位权展开均可。',
    difficulty: 'easy', tags: ['数制转换'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-31', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '逻辑函数 F=AB+AC 化简后为？', options: ['A(B+C)', 'A+B+C', '(A+B)(A+C)', 'ABC'],
    answer: 'A', analysis: '提取公因子 A：F=A(B+C)。(A+B)(A+C)=A+BC 是另一个常用恒等式，注意区分。',
    difficulty: 'easy', tags: ['逻辑代数', '化简'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-32', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '异或门 F=A⊕B，当 A=1 时 F=？', options: ['B', '1', '0', 'B\''],
    answer: 'D', analysis: 'A=1 时 F=1⊕B=B\'。异或门可作可控反相器：A=0 时 F=B，A=1 时 F=B\'。',
    difficulty: 'easy', tags: ['逻辑门', '异或'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-33', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '半加器与全加器的区别是半加器？', options: ['不考虑低位进位', '考虑低位进位', '输出两个进位', '需要三个输入'],
    answer: 'A', analysis: '半加器只有两个输入（两个本位加数），不考虑低位进位；全加器多一个低位进位输入。',
    difficulty: 'easy', tags: ['加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-34', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '全加器共有几个输入端？', options: ['2个', '4个', '5个', '3个'],
    answer: 'D', analysis: '全加器输入为本位加数 A、B 和低位进位 Ci 共 3 个，输出为本位和 S 和进位 Co。',
    difficulty: 'easy', tags: ['加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-35', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '8 线-3 线优先编码器输出为几位二进制代码？', options: ['2位', '4位', '8位', '3位'],
    answer: 'D', analysis: '编码器 n 个输入对应 log2n 位输出：8 输入→3 位（2³=8）。',
    difficulty: 'easy', tags: ['编码器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-36', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '74LS138 属于哪种译码器？', options: ['2线-4线', '4线-16线', '8线-3线', '3线-8线'],
    answer: 'D', analysis: '74LS138 是 3线-8线译码器，常用于构成数据分配器或实现组合逻辑函数。',
    difficulty: 'easy', tags: ['译码器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-37', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: '基本 RS 触发器 R=1、S=0 时，Q 的状态为？', options: ['置1', '置0', '翻转', '保持'],
    answer: 'B', analysis: 'S=1 置1、R=1 置0、S=R=0 保持、S=R=1 为禁止态（输出不确定）。注意 S 对应置位。',
    difficulty: 'easy', tags: ['RS触发器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-38', subject: 'electronics', chapter: '脉冲波形的产生与整形', type: 'single',
    stem: '施密特触发器的主要特点是？', options: ['有滞回特性（回差电压）', '无滞回特性', '只能触发一次', '输出恒为高电平'],
    answer: 'A', analysis: '施密特触发器具有上、下两个阈值电压（回差），能把缓慢变化的信号整形为矩形波，抗干扰能力强。',
    difficulty: 'medium', tags: ['施密特触发器', '波形整形'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-39', subject: 'electronics', chapter: '脉冲波形的产生与整形', type: 'single',
    stem: '555 定时器构成多谐振荡器时，输出波形为？', options: ['方波', '正弦波', '三角波', '锯齿波'],
    answer: 'A', analysis: '多谐振荡器（无稳态）输出矩形波/方波；555 还可构成施密特触发器和单稳态触发器。',
    difficulty: 'medium', tags: ['555定时器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-40', subject: 'electronics', chapter: '直流稳压电源', type: 'single',
    stem: '桥式整流加电容滤波后，空载输出电压约为副边电压有效值的？', options: ['0.45U2', '0.9U2', '1.2U2', '1.41U2'],
    answer: 'D', analysis: '电容滤波空载时 Uo≈√2U2=1.41U2，带负载后约 1.2U2；纯桥式整流 0.9U2，半波 0.45U2。',
    difficulty: 'medium', tags: ['整流滤波'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 高数扩充二（math-13..30，共 18 题）=====
  { id: 'math-13', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→∞) (1+1/x)ˣ = ?', options: ['1', '∞', 'e', '0'],
    answer: 'C', analysis: '这是第二个重要极限 lim(1+1/x)ˣ=e。第一个重要极限是 lim(sin x/x)=1 (x→0)。',
    difficulty: 'easy', tags: ['重要极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-14', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→2) (x²-4)/(x-2) = ?', options: ['0', '2', '不存在', '4'],
    answer: 'D', analysis: '分子因式分解 (x-2)(x+2)，约去 x-2 得 lim(x+2)=4。这是 0/0 型未定式。',
    difficulty: 'easy', tags: ['极限', '未定式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-15', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '导数定义中，f\'(x₀) 等于？', options: ['lim(h→∞) [f(x₀+h)-f(x₀)]/h', 'lim(h→0) [f(x₀+h)+f(x₀)]/h', 'lim(h→0) [f(x₀+h)-f(x₀)]/h', 'lim(h→0) [f(x₀)-f(x₀+h)]/h'],
    answer: 'C', analysis: '导数是函数增量与自变量增量之比在增量趋于 0 时的极限，几何意义是切线的斜率。',
    difficulty: 'easy', tags: ['导数定义'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-16', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y=sin x 的导数是？', options: ['-cos x', '-sin x', 'tan x', 'cos x'],
    answer: 'D', analysis: '(sin x)\'=cos x，(cos x)\'=-sin x。求导公式要记牢。',
    difficulty: 'easy', tags: ['求导公式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-17', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y=ln x 的导数是？', options: ['x', 'ln x', '1/ln x', '1/x'],
    answer: 'D', analysis: '(ln x)\'=1/x，(eˣ)\'=eˣ。对数求导公式是高频考点。',
    difficulty: 'easy', tags: ['求导公式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-18', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '复合函数 y=(2x+1)³ 的导数 y\' = ?', options: ['3(2x+1)²', '3(2x+1)²·2x', '6(2x+1)', '6(2x+1)²'],
    answer: 'D', analysis: '链式法则：y\'=3(2x+1)²·(2x+1)\'=3(2x+1)²·2=6(2x+1)²。',
    difficulty: 'medium', tags: ['复合函数求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-19', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '罗尔定理的三个条件是？', options: ['闭区间连续、开区间可导', '开区间可导、端点值相等', '闭区间连续、开区间可导、端点值相等', '闭区间连续、端点值相等'],
    answer: 'C', analysis: '罗尔定理需要三个条件缺一不可：①闭区间连续 ②开区间可导 ③f(a)=f(b)，结论是存在 ξ 使 f\'(ξ)=0。',
    difficulty: 'medium', tags: ['罗尔定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-20', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '拉格朗日中值定理的结论是？', options: ['存在 ξ 使 f(b)-f(a)=f\'(ξ)(b-a)', '存在 ξ 使 f\'(ξ)=0', 'f(b)=f(a)', '存在 ξ 使 f\'(ξ)=f(ξ)'],
    answer: 'A', analysis: '拉格朗日中值定理：存在 ξ∈(a,b)，使 f(b)-f(a)=f\'(ξ)(b-a)。罗尔定理是它的特例。',
    difficulty: 'medium', tags: ['拉格朗日中值定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-21', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '函数 y=x² 在 [1,3] 上满足拉格朗日中值定理的 ξ = ?', options: ['1', '3', '4', '2'],
    answer: 'D', analysis: 'f\'(x)=2x，f(3)-f(1)=9-1=8=2ξ·(3-1)=4ξ，得 ξ=2。',
    difficulty: 'medium', tags: ['拉格朗日中值定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-22', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '不定积分 ∫(2x+3)dx = ?', options: ['2x²+3x+C', 'x²+3+C', 'x²+3x+C', '2x+3x+C'],
    answer: 'C', analysis: '∫2x dx=x²，∫3dx=3x，加任意常数 C。逐项积分再合并。',
    difficulty: 'easy', tags: ['不定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-23', subject: 'math', chapter: '定积分', type: 'single',
    stem: '定积分 ∫₀^π sin x dx = ?', options: ['1', '0', '2', '-2'],
    answer: 'C', analysis: '∫sin x dx=-cos x，代入上下限：-cos π-(-cos 0)=1+1=2。',
    difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-24', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '用分部积分法计算 ∫x·eˣ dx = ?', options: ['eˣ(x+1)+C', 'x²eˣ/2+C', 'eˣ(x²-1)+C', 'eˣ(x-1)+C'],
    answer: 'D', analysis: '分部积分：∫x·eˣdx=x·eˣ-∫eˣdx=eˣ(x-1)+C。选 u=x、dv=eˣdx。',
    difficulty: 'hard', tags: ['分部积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-25', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '微分方程 y\'=2x 的通解为？', options: ['y=x²+C', 'y=2x+C', 'y=x²+2x+C', 'y=2x²+C'],
    answer: 'A', analysis: '两边直接积分：y=∫2x dx=x²+C。',
    difficulty: 'easy', tags: ['微分方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-26', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '二阶齐次微分方程 y\'\'-y=0 的通解为？', options: ['y=C₁cos x+C₂sin x', 'y=C₁eˣ+C₂x', 'y=C₁+C₂x', 'y=C₁eˣ+C₂e⁻ˣ'],
    answer: 'D', analysis: '特征方程 r²-1=0，r=±1，通解 y=C₁eˣ+C₂e⁻ˣ。特征根为两个不等实根。',
    difficulty: 'hard', tags: ['微分方程', '特征方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-27', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: 'p-级数 Σ(1/n²) 的敛散性是？', options: ['发散', '收敛', '条件收敛', '无法判断'],
    answer: 'B', analysis: 'p-级数 Σ1/nᵖ：p>1 收敛，p≤1 发散。p=2>1，故收敛（且绝对收敛）。',
    difficulty: 'medium', tags: ['p级数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-28', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: '交错级数 Σ(-1)ⁿ/n 的敛散性是？', options: ['绝对收敛', '发散', '条件收敛', '无法判断'],
    answer: 'C', analysis: 'Σ|(-1)ⁿ/n|=Σ1/n 发散，但交错级数本身满足莱布尼茨判别法收敛，故为条件收敛。',
    difficulty: 'hard', tags: ['交错级数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-29', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '设 z=eˣʸ，则 ∂z/∂y = ?', options: ['x·eˣʸ', 'y·eˣʸ', 'eˣʸ', 'xy·eˣʸ'],
    answer: 'A', analysis: '对 y 求偏导时 x 视为常数：∂(eˣʸ)/∂y=eˣʸ·(xy)\'ₓ=eˣʸ·x。',
    difficulty: 'medium', tags: ['偏导数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-30', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '函数 z=x²+y² 的全微分 dz = ?', options: ['xdx+ydy', '2xdx+2ydy', '2x+2y', 'x²dx+y²dy'],
    answer: 'B', analysis: 'dz=(∂z/∂x)dx+(∂z/∂y)dy=2xdx+2ydy。全微分是偏导数与微分的线性组合。',
    difficulty: 'medium', tags: ['全微分'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 英语扩充二（english-9..25，共 17 题）=====
  { id: 'english-9', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'She ___ English since 2020.', options: ['studied', 'was studying', 'has been studying', 'studies'],
    answer: 'C', analysis: 'since+时间点用现在完成进行时 have/has been doing，强调动作持续进行。',
    difficulty: 'medium', tags: ['时态', '完成进行时'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-10', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The bridge ___ in 1990.', options: ['built', 'is built', 'was built', 'builds'],
    answer: 'C', analysis: '桥是被建造的，用被动语态 was built，且 1990 是过去时间。',
    difficulty: 'easy', tags: ['被动语态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-11', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The more you read, ___ you will understand.', options: ['the best', 'better', 'best', 'the better'],
    answer: 'D', analysis: '"the+比较级...，the+比较级..."结构：越...就越...。',
    difficulty: 'medium', tags: ['比较级'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-12', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He must ___ the train; he left home at 7 and it leaves at 7:30.', options: ['miss', 'be missing', 'missed', 'have missed'],
    answer: 'D', analysis: 'must have done 表示对过去情况的肯定推测：他一定错过了火车。',
    difficulty: 'hard', tags: ['情态动词', '推测'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-13', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: '___ is good for your health.', options: ['Swim', 'Swimming', 'Swam', 'To swimming'],
    answer: 'B', analysis: '动名词（-ing 形式）作主语表一般性动作。不定式作主语也可，但此处选项只有 A 合适。',
    difficulty: 'easy', tags: ['非谓语动词', '动名词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-14', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'Neither of the two answers ___ correct.', options: ['are', 'were', 'have been', 'is'],
    answer: 'D', analysis: 'neither of + 复数名词作主语，谓语用单数（neither 表示"两者都不"）。',
    difficulty: 'medium', tags: ['主谓一致'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-15', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: '___ it was raining, we went out.', options: ['Although', 'Because', 'So', 'Unless'],
    answer: 'A', analysis: 'although 引导让步状语从句：尽管下雨，我们还是出去了。',
    difficulty: 'easy', tags: ['连词', '让步状语'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-16', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'She is good ___ playing the piano.', options: ['in', 'on', 'for', 'at'],
    answer: 'D', analysis: 'be good at 擅长...。固定搭配要记牢。',
    difficulty: 'easy', tags: ['介词搭配'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-17', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "abandon" 最接近的意思是？', options: ['give up', 'keep up', 'turn up', 'pick up'],
    answer: 'A', analysis: 'abandon = give up（放弃、抛弃）。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-18', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "acquire" 最接近的意思是？', options: ['lose', 'obtain', 'avoid', 'require'],
    answer: 'B', analysis: 'acquire = obtain（获得、习得）。acquire knowledge 获取知识。',
    difficulty: 'medium', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-19', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "efficient" 的意思是？', options: ['高效的', '充足的', '有效的', '昂贵的'],
    answer: 'A', analysis: 'efficient 高效的（以最少浪费达到目的）；effective 有效的（达到预期效果），两词常混考。',
    difficulty: 'medium', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-20', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "significant" 最接近的意思是？', options: ['次要的', '明显的', '重要的', '普遍的'],
    answer: 'C', analysis: 'significant = important（重要的、显著的）。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-21', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "schedule" 的意思是？', options: ['奖学金', '学期', '评分', '时间表、日程'],
    answer: 'D', analysis: 'schedule 时间表、日程安排。on schedule 按计划，ahead of schedule 提前。',
    difficulty: 'easy', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-22', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "approach" 的意思是？', options: ['责备', '方法、接近', '加速', '撤退'],
    answer: 'B', analysis: 'approach 作名词"方法"（a new approach to the problem），作动词"接近"。',
    difficulty: 'medium', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-23', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He is a student, ___?', options: ['is he', 'does he', 'isn\'t he', 'doesn\'t he'],
    answer: 'C', analysis: '反义疑问句：前肯后否。is a student 是肯定句，疑问尾用 isn\'t he。',
    difficulty: 'easy', tags: ['反义疑问句'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-24', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He was ___ tired ___ he fell asleep at once.', options: ['so; that', 'such; that', 'too; to', 'very; that'],
    answer: 'A', analysis: 'so...that 如此...以至于（接从句）。such...that 修饰名词，too...to 表"太...而不能"。',
    difficulty: 'medium', tags: ['结果状语从句'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-25', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The work ___ by the end of this month.', options: ['will have been finished', 'will have finished', 'will be finishing', 'finishes'],
    answer: 'A', analysis: 'by+将来时间点用将来完成时；工作是被完成的，故用将来完成被动 will have been finished。',
    difficulty: 'hard', tags: ['时态', '被动语态'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 政治扩充二（politics-9..25，共 17 题）=====
  { id: 'politics-9', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '量变是质变的必要准备，质变是量变的必然结果，这一规律是？', options: ['对立统一规律', '质量互变规律', '否定之否定规律', '价值规律'],
    answer: 'B', analysis: '质量互变规律揭示了事物发展的状态和形式：量变→质变→新的量变。',
    difficulty: 'easy', tags: ['辩证法', '质量互变'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-10', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '实践的基本形式不包括？', options: ['物质生产实践', '社会政治实践', '科学文化实践', '个人消费实践'],
    answer: 'D', analysis: '实践的三种基本形式：物质生产实践（基础）、社会政治实践、科学文化实践。个人消费不属于基本形式。',
    difficulty: 'medium', tags: ['实践', '认识论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-11', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '真理的客观性是指？', options: ['真理的形式是客观的', '真理是多数人认同的', '真理是永恒不变的', '真理的内容是客观的'],
    answer: 'D', analysis: '真理客观性：内容来自客观世界，不依人的意志为转移。真理的形式（判断、概念）是主观的。',
    difficulty: 'medium', tags: ['真理观'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-12', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '新民主主义革命的三大法宝是？', options: ['实事求是、群众路线、独立自主', '武装斗争、土地革命、根据地建设', '统一战线、武装斗争、党的建设', '统一战线、土地革命、党的建设'],
    answer: 'C', analysis: '三大法宝：统一战线、武装斗争、党的建设。注意与"活的灵魂"（实事求是、群众路线、独立自主）区分。',
    difficulty: 'easy', tags: ['新民主主义革命', '三大法宝'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-13', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'single',
    stem: '毛泽东思想的精髓是？', options: ['群众路线', '实事求是', '独立自主', '武装斗争'],
    answer: 'B', analysis: '实事求是是毛泽东思想的精髓，也是党的思想路线的核心。',
    difficulty: 'easy', tags: ['毛泽东思想'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-14', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '1949 年新中国成立后到 1956 年，我国社会的主要矛盾是？', options: ['无产阶级与资产阶级的矛盾', '人民日益增长的物质文化需要同落后的社会生产之间的矛盾', '人民对于建立先进的工业国的要求同落后的农业国的现实之间的矛盾', '生产力和生产关系之间的矛盾'],
    answer: 'C', analysis: '过渡时期主要矛盾：人民对于建立先进的工业国的要求同落后的农业国的现实之间的矛盾，即社会主义道路与资本主义道路的矛盾。',
    difficulty: 'hard', tags: ['过渡时期', '主要矛盾'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-15', subject: 'politics', chapter: '社会主义改造理论', type: 'single',
    stem: '社会主义改造基本完成的标志是？', options: ['1954 年宪法颁布', '1956 年三大改造基本完成', '1952 年土改完成', '1958 年人民公社化'],
    answer: 'B', analysis: '1956 年底对农业、手工业、资本主义工商业的社会主义改造基本完成，社会主义基本制度确立。',
    difficulty: 'medium', tags: ['社会主义改造'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-16', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"两个一百年"奋斗目标中，第一个百年目标指？', options: ['基本实现现代化', '全面建成小康社会', '建成社会主义现代化强国', '实现共同富裕'],
    answer: 'B', analysis: '第一个百年（建党 100 年，2021 年）：全面建成小康社会，已如期完成；第二个百年（建国 100 年，2049 年）：建成社会主义现代化强国。',
    difficulty: 'easy', tags: ['两个一百年'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-17', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '新发展理念的内容是？', options: ['创新、协调、绿色、开放、共享', '改革、发展、稳定、创新、协调', '创新、协调、绿色、改革、开放', '发展、协调、绿色、开放、共赢'],
    answer: 'A', analysis: '新发展理念：创新（第一动力）、协调（内生特点）、绿色（普遍形态）、开放（必由之路）、共享（本质要求）。',
    difficulty: 'easy', tags: ['新发展理念'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-18', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"五位一体"总体布局是？', options: ['经济建设、政治建设、文化建设、国防建设、党的建设', '工业化、信息化、城镇化、农业现代化、绿色化', '道路自信、理论自信、制度自信、文化自信、生态自信', '经济建设、政治建设、文化建设、社会建设、生态文明建设'],
    answer: 'D', analysis: '五位一体：经济、政治、文化、社会、生态文明建设。注意与"四个全面"（全面建成小康社会、全面深化改革、全面依法治国、全面从严治党）区分。',
    difficulty: 'medium', tags: ['五位一体'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-19', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '全面深化改革的总目标是？', options: ['完善和发展中国特色社会主义制度，推进国家治理体系和治理能力现代化', '全面建成小康社会', '建设社会主义现代化强国', '实现中华民族伟大复兴'],
    answer: 'A', analysis: '全面深化改革总目标：完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化。',
    difficulty: 'medium', tags: ['全面深化改革'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-20', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '乡村振兴战略的总要求是？', options: ['产业兴旺、生态宜居、乡风文明、治理有效、生活富裕', '生产发展、生活宽裕、乡风文明、村容整洁、管理民主', '产业兴旺、生态宜居、乡风文明、治理有效、共同富裕', '农业强、农村美、农民富'],
    answer: 'A', analysis: '乡村振兴二十字总要求：产业兴旺、生态宜居、乡风文明、治理有效、生活富裕。选项 B 是新农村建设旧提法。',
    difficulty: 'medium', tags: ['乡村振兴'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-21', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '总体国家安全观的宗旨是？', options: ['人民安全', '政治安全', '经济安全', '军事安全'],
    answer: 'A', analysis: '总体国家安全观以人民安全为宗旨、以政治安全为根本、以经济安全为基础。',
    difficulty: 'medium', tags: ['国家安全'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-22', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '2025 年《政府工作报告》提出的国内生产总值增长预期目标是？', options: ['4%左右', '4.5%左右', '5%左右', '5.5%左右'],
    answer: 'C', analysis: '2025 年政府工作报告提出 GDP 增长预期目标 5% 左右，与 2024 年持平。',
    difficulty: 'medium', tags: ['时政', '2025'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-23', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"十五五"规划的时间范围是？', options: ['2021-2025年', '2025-2030年', '2026-2030年', '2030-2035年'],
    answer: 'C', analysis: '"十五五"规划即第十五个五年规划，覆盖 2026-2030 年，2025 年 10 月党的二十届四中全会通过建议。',
    difficulty: 'hard', tags: ['时政', '十五五'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-24', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '人类社会发展的基本规律是？', options: ['生产关系一定要适合生产力状况的规律', '上层建筑一定要适合经济基础状况的规律', '价值规律', '剩余价值规律'],
    answer: 'A', analysis: '人类社会两大基本规律：生产关系一定要适合生产力状况、上层建筑一定要适合经济基础状况。A 是最基本的。',
    difficulty: 'medium', tags: ['唯物史观'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-25', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '唯物辩证法认为事物发展的源泉和动力是？', options: ['内部矛盾', '外部矛盾', '外力推动', '量的积累'],
    answer: 'A', analysis: '内因（内部矛盾）是事物发展的源泉和根本动力，外因通过内因起作用。',
    difficulty: 'easy', tags: ['辩证法', '矛盾'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 多选 / 判断 / 填空 题型补充（电子技术） ======
  { id: 'elec-m1', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'multiple',
    stem: '下列哪些电路组态具有电压放大能力？（多选）', options: ['共射', '共集', '共基', '共源'],
    answer: 'AC', analysis: '共射和共基具有电压放大能力；共集（射随器）电压增益≈1，主要做阻抗变换。',
    difficulty: 'medium', tags: ['BJT', '组态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-m2', subject: 'electronics', chapter: '集成运算放大器', type: 'multiple',
    stem: '理想运放的主要特点包括？（多选）', options: ['开环增益无穷大', '输入电阻无穷大', '输出电阻为零', '带宽有限'],
    answer: 'ABC', analysis: '理想运放：开环增益、输入电阻无穷大，输出电阻为零，带宽无穷大。',
    difficulty: 'easy', tags: ['运放'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-t1', subject: 'electronics', chapter: '半导体二极管', type: 'truefalse',
    stem: '硅二极管正向导通时，管压降近似为0.7V。', answer: '对',
    analysis: '硅管正向导通压降约0.6-0.7V，锗管约0.2-0.3V。',
    difficulty: 'easy', tags: ['二极管'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-t2', subject: 'electronics', chapter: '组合逻辑电路', type: 'truefalse',
    stem: '异或门的输出在输入相同时为1。', answer: '错',
    analysis: '异或门：输入相同时输出0，输入不同时输出1。',
    difficulty: 'easy', tags: ['逻辑门'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-f1', subject: 'electronics', chapter: '集成运算放大器', type: 'fill',
    stem: '理想运放两输入端电位近似相等的现象称为____（两个字）。', answer: '虚短',
    analysis: '虚短：负反馈深度足够时两输入端电位近似相等；虚断：输入电流近似为0。',
    difficulty: 'easy', tags: ['运放'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 多选 / 判断 / 填空 题型补充（高数） ======
  { id: 'math-m1', subject: 'math', chapter: '函数与极限', type: 'multiple',
    stem: '下列极限值为1的有？（多选）', options: ['lim(x→0) sinx/x', 'lim(x→∞) (1+1/x)^x', 'lim(x→0) x·sin(1/x)', 'lim(x→0) (e^x-1)/x'],
    answer: 'ABD', analysis: '第一个重要极限、e的定义、等价无穷小均为1；x·sin(1/x) 极限为0（无穷小乘有界量）。',
    difficulty: 'medium', tags: ['极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-t1', subject: 'math', chapter: '导数与微分', type: 'truefalse',
    stem: '可导必连续，连续不一定可导。', answer: '对',
    analysis: '可导是连续的充分条件；如 |x| 在 x=0 处连续但不可导。',
    difficulty: 'easy', tags: ['导数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-f1', subject: 'math', chapter: '函数与极限', type: 'fill',
    stem: 'lim(x→0) sin x / x = ____', answer: '1',
    analysis: '第一个重要极限，结果为1。',
    difficulty: 'easy', tags: ['极限'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 判断 / 填空 题型补充（英语） ======
  { id: 'eng-t1', subject: 'english', chapter: '基本语法规则', type: 'truefalse',
    stem: '一般现在时中，主语为第三人称单数时动词需加 -s 或 -es。', answer: '对',
    analysis: '第三人称单数一般现在时：动词加 -s/-es，如 he goes。',
    difficulty: 'easy', tags: ['时态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-f1', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: 'He ____ (go) to school every day. 请写出动词的正确形式。', answer: 'goes',
    analysis: '第三人称单数一般现在时，go 加 -es 变 goes。',
    difficulty: 'easy', tags: ['时态'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 判断 / 填空 题型补充（政治） ======
  { id: 'pol-t1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'truefalse',
    stem: '实践是检验真理的唯一标准。', answer: '对',
    analysis: '马克思主义认识论的基本观点：实践是检验真理的唯一标准。',
    difficulty: 'easy', tags: ['认识论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-f1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'fill',
    stem: '事物发展的根本原因是____（填：内部矛盾/外部矛盾）。', answer: '内部矛盾',
    analysis: '内因是事物发展的根本原因，外因通过内因起作用。',
    difficulty: 'easy', tags: ['辩证法'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 2026-08-01 内容增强批：题型补齐（多选/判断/填空/简答/论述）+ 考纲深度覆盖 =====
  // 电子技术（200 分大科，重点补计算/填空）
  { id: 'elec-101', subject: 'electronics', chapter: '集成运算放大器', type: 'fill',
    stem: '理想运放两个重要特性：同相输入端与反相输入端电位近似相等称为"虚短"，输入电流近似为零称为"____"。', options: undefined,
    answer: '虚断', analysis: '虚短：u+ ≈ u-；虚断：i+ ≈ i- ≈ 0（由输入电阻无穷大保证）。', difficulty: 'easy', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-102', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'fill',
    stem: 'BJT 工作在放大区的外部条件是发射结____偏置、集电结____偏置。', options: undefined,
    answer: '正反', analysis: '放大区：发射结正偏、集电结反偏。', difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-103', subject: 'electronics', chapter: '反馈放大电路', type: 'fill',
    stem: '电压串联负反馈可使输出电阻____（填"增大"或"减小"），输入电阻增大。', options: undefined,
    answer: '减小', analysis: '电压负反馈稳定输出电压、减小输出电阻；串联负反馈增大输入电阻。', difficulty: 'medium', tags: ['负反馈', '反馈类型'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-104', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'fill',
    stem: 'n 个触发器组成的二进制计数器，最大可计数的模值为____。', options: undefined,
    answer: '2^n', analysis: 'n 位二进制计数器模值为 2ⁿ。', difficulty: 'medium', tags: ['时序电路', '计数器'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-105', subject: 'electronics', chapter: '集成运算放大器', type: 'short',
    stem: '反相比例运算电路中，R1=10kΩ，Rf=100kΩ，输入电压 ui=0.2V，求输出电压 uo。', options: undefined,
    answer: '-2V', analysis: 'uo = -(Rf/R1)·ui = -(100/10)×0.2 = -2V。反相放大倍数为 -Rf/R1。', difficulty: 'medium', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-106', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'short',
    stem: '共射放大电路，Vcc=12V，Rc=3kΩ，静态集电极电流 Ic=2mA，求静态管压降 Uce（忽略饱和压降）。', options: undefined,
    answer: '6V', analysis: 'Uce = Vcc - Ic·Rc = 12 - 2×3 = 6V。', difficulty: 'medium', tags: ['BJT', '静态工作点'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-107', subject: 'electronics', chapter: '组合逻辑电路', type: 'short',
    stem: "化简逻辑函数 F = AB + A'B' 的结果是什么？（用最简与或式）", options: undefined,
    answer: 'A⊙B', analysis: "F = AB + A'B' 是同或运算，记为 A⊙B。", difficulty: 'medium', tags: ['逻辑代数', '化简'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-108', subject: 'electronics', chapter: '直流稳压电源', type: 'short',
    stem: '桥式整流电容滤波电路中，变压器副边电压有效值 U2=20V，空载时输出电压约为多少伏？', options: undefined,
    answer: '28V', analysis: '空载时电容充电到峰值，Uo ≈ 1.4·U2 = 28V（有负载时约 1.2·U2 = 24V）。', difficulty: 'medium', tags: ['整流滤波', '直流电源'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-109', subject: 'electronics', chapter: '反馈放大电路', type: 'multiple',
    stem: '负反馈对放大电路性能的改善包括（多选）：', options: ['提高放大倍数', '稳定放大倍数', '展宽通频带', '减小非线性失真'],
    answer: 'BCD', analysis: '负反馈以牺牲放大倍数（减小）换取稳定性：稳定增益、展宽频带、改善非线性失真、改变输入输出电阻。', difficulty: 'medium', tags: ['负反馈'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-110', subject: 'electronics', chapter: '集成运算放大器', type: 'multiple',
    stem: '理想运放的特点包括（多选）：', options: ['开环增益无穷大', '输入电阻无穷大', '输出电阻为零', '带宽无穷大'],
    answer: 'ABCD', analysis: '理想运放四要素：开环增益∞、输入电阻∞、输出电阻0、带宽∞。', difficulty: 'easy', tags: ['运放'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-111', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'multiple',
    stem: '下列属于时序逻辑电路的有（多选）：', options: ['加法器', '计数器', '寄存器', '编码器'],
    answer: 'BC', analysis: '时序电路有记忆功能（含触发器）：计数器、寄存器。加法器/编码器是组合逻辑电路。', difficulty: 'medium', tags: ['时序电路'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-112', subject: 'electronics', chapter: '直流稳压电源', type: 'truefalse',
    stem: '稳压二极管正常工作在反向击穿区。', options: ['对', '错'],
    answer: 'A', analysis: '稳压管利用反向击穿特性稳压，工作于反向击穿区。', difficulty: 'easy', tags: ['稳压管'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-113', subject: 'electronics', chapter: '多级放大电路', type: 'truefalse',
    stem: '共集电极放大电路（射极跟随器）的电压增益大于 1。', options: ['对', '错'],
    answer: 'B', analysis: '射极跟随器电压增益约等于 1（略小于 1），主要起阻抗变换作用。', difficulty: 'medium', tags: ['共集放大'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-114', subject: 'electronics', chapter: '半导体二极管', type: 'single',
    stem: '二极管正向导通后，其正向压降（硅管）约为？', options: ['0.1V', '0.3V', '0.7V', '1.2V'],
    answer: 'C', analysis: '硅管正向压降约 0.7V，锗管约 0.3V。', difficulty: 'easy', tags: ['二极管'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'elec-115', subject: 'electronics', chapter: '功率放大电路', type: 'single',
    stem: 'OCL 互补对称功放电路中，输出管工作在哪种状态时效率最高？', options: ['甲类', '乙类', '甲乙类', '丙类'],
    answer: 'B', analysis: '乙类理想效率 78.5%，但存在交越失真；实际用甲乙类兼顾效率与失真。', difficulty: 'medium', tags: ['功放'], source: 'manual', createdAt: '2026-08-01' },

  // 高数
  { id: 'math-101', subject: 'math', chapter: '函数与极限', type: 'fill',
    stem: 'lim(x→∞) (1 + 2/x)^x = ____。', options: undefined,
    answer: 'e^2', analysis: '重要极限 lim(1+k/x)^x = eᵏ，k=2 得 e²。', difficulty: 'medium', tags: ['极限', '重要极限'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-102', subject: 'math', chapter: '导数与微分', type: 'fill',
    stem: "函数 y = ln(x²+1) 在 x=1 处的导数 y'(1) = ____。", options: undefined,
    answer: '1', analysis: "y' = 2x/(x²+1)，y'(1) = 2/2 = 1。", difficulty: 'easy', tags: ['求导', '复合函数'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-103', subject: 'math', chapter: '定积分及其应用', type: 'fill',
    stem: '∫(0→π) sin x dx = ____。', options: undefined,
    answer: '2', analysis: '∫sin x dx = -cos x，代入上下限：-cos π + cos 0 = 1 + 1 = 2。', difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-104', subject: 'math', chapter: '微分方程', type: 'fill',
    stem: "微分方程 y' = y 的通解为 y = C·____。", options: undefined,
    answer: 'e^x', analysis: '可分离变量：dy/y = dx，ln|y| = x + C，y = Ceˣ。', difficulty: 'medium', tags: ['微分方程'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-105', subject: 'math', chapter: '函数与极限', type: 'short',
    stem: '求极限 lim(x→0) (1 - cos x) / x²。', options: undefined,
    answer: '1/2', analysis: '1 - cos x ~ x²/2 (x→0)，故原式 = (x²/2)/x² = 1/2。', difficulty: 'medium', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-106', subject: 'math', chapter: '不定积分', type: 'short',
    stem: '求不定积分 ∫ e^(2x) dx。', options: undefined,
    answer: '1/2e^(2x)+C', analysis: '∫e^(2x)dx = (1/2)e^(2x) + C。', difficulty: 'easy', tags: ['积分'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-107', subject: 'math', chapter: '定积分及其应用', type: 'short',
    stem: '计算定积分 ∫(0→1) (2x + 1) dx。', options: undefined,
    answer: '2', analysis: '∫(2x+1)dx = x² + x，代入 1、0：1+1 = 2。', difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-108', subject: 'math', chapter: '无穷级数', type: 'short',
    stem: '判断级数 Σ(1/n²)（n 从 1 到 ∞）的敛散性，收敛还是发散？', options: undefined,
    answer: '收敛', analysis: 'p-级数 Σ1/nᵖ，p=2>1 收敛。', difficulty: 'medium', tags: ['级数'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-109', subject: 'math', chapter: '函数与极限', type: 'multiple',
    stem: '当 x→0 时，下列与 x 等价的无穷小有（多选）：', options: ['sin x', 'tan x', '1 - cos x', 'ln(1+x)'],
    answer: 'ABD', analysis: 'sin x ~ x、tan x ~ x、ln(1+x) ~ x；而 1 - cos x ~ x²/2（二阶无穷小）。', difficulty: 'medium', tags: ['等价无穷小'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-110', subject: 'math', chapter: '导数与微分', type: 'multiple',
    stem: '函数 f(x) 在 x₀ 处可导是 f(x) 在 x₀ 处连续的什么条件（多选判断）：', options: ['充分条件', '必要条件', '充要条件', '既不充分也不必要'],
    answer: 'AB', analysis: '可导必连续（可导是连续的充分条件）；连续不一定可导（如 |x| 在 0 处）。', difficulty: 'easy', tags: ['可导', '连续'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-111', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'truefalse',
    stem: "若 f'(x₀) = 0，则 x₀ 一定是函数 f(x) 的极值点。", options: ['对', '错'],
    answer: 'B', analysis: '驻点不一定是极值点（如 y=x³ 在 x=0 处），还需二阶导或两侧符号判断。', difficulty: 'easy', tags: ['极值'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'math-112', subject: 'math', chapter: '定积分及其应用', type: 'truefalse',
    stem: '奇函数在对称区间 [-a, a] 上的定积分等于 0。', options: ['对', '错'],
    answer: 'A', analysis: '奇函数在对称区间积分关于原点抵消，∫(-a→a) f(x)dx = 0。', difficulty: 'easy', tags: ['定积分', '奇偶性'], source: 'manual', createdAt: '2026-08-01' },

  // 政治（补多选/简答/论述，对齐广东专升本题型）
  { id: 'pol-101', subject: 'politics', chapter: '马克思主义哲学原理', type: 'multiple',
    stem: '唯物辩证法的基本规律包括（多选）：', options: ['对立统一规律', '质量互变规律', '否定之否定规律', '价值规律'],
    answer: 'ABC', analysis: '三大基本规律：对立统一、质量互变、否定之否定。价值规律是商品经济规律，不属于辩证法基本规律。', difficulty: 'easy', tags: ['辩证法'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-102', subject: 'politics', chapter: '马克思主义哲学原理', type: 'multiple',
    stem: '实践的基本形式包括（多选）：', options: ['生产实践', '社会实践', '科学实验', '思维活动'],
    answer: 'ABC', analysis: '实践三种基本形式：生产实践、社会实践（处理社会关系）、科学实验。思维活动不属于实践。', difficulty: 'medium', tags: ['实践'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-103', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'multiple',
    stem: '中国特色社会主义进入新时代，我国社会主要矛盾是人民日益增长的____需要和____的发展之间的矛盾（多选填空）：', options: ['美好生活', '不平衡不充分', '物质文化', '落后'],
    answer: 'AB', analysis: '新时代主要矛盾：人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。', difficulty: 'medium', tags: ['习思想', '主要矛盾'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-104', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'multiple',
    stem: '新民主主义革命的三大法宝是（多选）：', options: ['统一战线', '武装斗争', '党的建设', '土地革命'],
    answer: 'ABC', analysis: '统一战线、武装斗争、党的建设是三大法宝。土地革命是革命内容之一，不是法宝。', difficulty: 'easy', tags: ['毛概', '新民主主义'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-105', subject: 'politics', chapter: '马克思主义哲学原理', type: 'short',
    stem: '简述矛盾的同一性和斗争性的辩证关系。', options: undefined,
    answer: '相互联结相互制约', analysis: '要点：同一性以斗争性为前提，斗争性寓于同一性之中；二者相互联结、相互制约，共同推动事物发展。', difficulty: 'medium', tags: ['矛盾'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-106', subject: 'politics', chapter: '马克思主义哲学原理', type: 'short',
    stem: '实践对认识的决定作用表现在哪些方面？（答出要点）', options: undefined,
    answer: '来源动力标准目的', analysis: '四个要点：实践是认识的来源、动力、检验真理的唯一标准、认识的目的。', difficulty: 'medium', tags: ['认识论'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-107', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'short',
    stem: '新时代坚持和发展中国特色社会主义的基本方略第一条是什么？（填空）', options: undefined,
    answer: '坚持党对一切工作的领导', analysis: '十四个坚持的第一条：坚持党对一切工作的领导。', difficulty: 'easy', tags: ['习思想'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-108', subject: 'politics', chapter: '新民主主义革命理论', type: 'short',
    stem: '新民主主义革命的总路线是什么？（要点）', options: undefined,
    answer: '无产阶级领导的工农联盟为基础的人民大众反帝反封建反官僚资本主义', analysis: '总路线：无产阶级领导的，人民大众的，反对帝国主义、封建主义和官僚资本主义的革命。', difficulty: 'hard', tags: ['新民主主义'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-109', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'essay',
    stem: '论述：为什么说高质量发展是全面建设社会主义现代化国家的首要任务？', options: undefined,
    answer: '要点：1.经济基础决定上层建筑；2.解决社会主要矛盾的需要；3.构建新发展格局的必然要求；4.应对国际竞争的战略选择', analysis: '自评参考：从经济发展规律、主要矛盾、国际形势三个层面展开，结合二十大报告表述。', difficulty: 'hard', tags: ['习思想', '高质量发展'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-110', subject: 'politics', chapter: '马克思主义哲学原理', type: 'essay',
    stem: '论述：运用唯物辩证法联系的观点，分析如何统筹发展和安全。', options: undefined,
    answer: '要点：1.联系具有普遍性客观性；2.发展和安全相互依存相互促进；3.以新安全格局保障新发展格局', analysis: '自评参考：先阐述联系的观点原理，再结合发展和安全的辩证关系展开论证。', difficulty: 'hard', tags: ['辩证法', '联系'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-111', subject: 'politics', chapter: '马克思主义哲学原理', type: 'truefalse',
    stem: '真理是有条件的、具体的，任何真理都有自己适用的条件和范围。', options: ['对', '错'],
    answer: 'A', analysis: '真理的相对性：任何真理都是在一定条件下对客观事物一定层次的正确认识。', difficulty: 'easy', tags: ['真理'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-112', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'truefalse',
    stem: '毛泽东思想是毛泽东个人全部言论和思想的汇集。', options: ['对', '错'],
    answer: 'B', analysis: '毛泽东思想是集体智慧的结晶，是经过实践检验的正确理论，不是个人思想的简单汇集。', difficulty: 'easy', tags: ['毛概'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'pol-113', subject: 'politics', chapter: '社会主义改造理论', type: 'truefalse',
    stem: '我国社会主义改造完成后，社会主要矛盾转化为人民对于经济文化迅速发展的需要同当前经济文化不能满足这种需要的状况之间的矛盾。', options: ['对', '错'],
    answer: 'A', analysis: '八大指出：改造完成后主要矛盾是人民对于经济文化迅速发展的需要同当前经济文化不能满足这种需要的状况之间的矛盾。', difficulty: 'medium', tags: ['社会主义改造'], source: 'manual', createdAt: '2026-08-01' },

  // 英语（补填空/多选，细化语法点）
  { id: 'eng-101', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: 'She has lived in Guangzhou ___ 2015.（用介词填空）', options: undefined,
    answer: 'since', analysis: '现在完成时 + since + 过去时间点（2015）。', difficulty: 'easy', tags: ['时态', '介词'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-102', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: 'The meeting will be held ___ next Monday.（用介词或省略）', options: undefined,
    answer: '省略', analysis: 'next/last/this 等时间词前不加介词，直接省略。', difficulty: 'medium', tags: ['介词'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-103', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: "I'm looking forward to ___ (hear) from you.（用动词正确形式）", options: undefined,
    answer: 'hearing', analysis: 'look forward to 中 to 是介词，后接动名词 hearing。', difficulty: 'medium', tags: ['非谓语'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-104', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: 'The more you read, the ___ (easy) it will become.（用比较级）', options: undefined,
    answer: 'easier', analysis: 'the + 比较级, the + 比较级 结构：越……越……。', difficulty: 'easy', tags: ['比较级'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-105', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'This is the factory ___ we visited last year.', options: ['where', 'which', 'what', 'when'],
    answer: 'B', analysis: '先行词 factory 在从句中作 visited 的宾语，用关系代词 which（that 亦可）。', difficulty: 'medium', tags: ['定语从句'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-106', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'Not until he arrived at the station ___ the train had left.', options: ['he realized', 'did he realize', 'he did realize', 'realized he'],
    answer: 'B', analysis: 'Not until 置于句首，主句部分倒装：did + 主语 + 动词原形。', difficulty: 'hard', tags: ['倒装'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-107', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'You ___ have told me earlier. I waited for you for two hours!', options: ['should', 'must', 'could', 'might'],
    answer: 'A', analysis: 'should have done：本该做而未做（责备/后悔）。', difficulty: 'medium', tags: ['情态动词'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-108', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'It is essential that everyone ___ the rules.', options: ['obey', 'obeys', 'obeyed', 'will obey'],
    answer: 'A', analysis: 'essential 后接虚拟语气 should do（should 可省略），用动词原形。', difficulty: 'hard', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-109', subject: 'english', chapter: '基本语法规则', type: 'multiple',
    stem: '下列句子中，时态使用正确的有（多选）：', options: ['I have seen this film twice.', 'She has gone to Beijing last week.', 'They have lived here since 2020.', 'He has finished his homework just now.'],
    answer: 'AC', analysis: 'B 错：last week 用一般过去时（went）；D 错：just now 用一般过去时。A/C 现在完成时搭配正确。', difficulty: 'medium', tags: ['时态'], source: 'manual', createdAt: '2026-08-01' },
  { id: 'eng-110', subject: 'english', chapter: '基本语法规则', type: 'multiple',
    stem: '下列短语中，搭配正确的有（多选）：', options: ['depend on', 'agree with', 'look forward to', 'consist in to'],
    answer: 'ABC', analysis: 'consist in（在于）后直接接名词，无 to；正确搭配：depend on / agree with / look forward to。', difficulty: 'medium', tags: ['短语搭配'], source: 'manual', createdAt: '2026-08-01' },


  // ===== 2026-08-01 题型-分值匹配批（对齐真实考试结构） =====
  { id: "elec-201", subject: "electronics", chapter: "半导体二极管", type: "fill",
    stem: "硅二极管正向导通压降约为____V。", options: undefined,
    answer: "0.7", analysis: "硅管 0.7V，锗管 0.3V。", difficulty: "easy", tags: ["二极管"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-202", subject: "electronics", chapter: "双极结型三极管(BJT)及其放大电路", type: "fill",
    stem: "BJT 的电流放大系数 β 定义为集电极电流与____电流之比。", options: undefined,
    answer: "基极", analysis: "β = Ic/Ib，共射直流放大系数。", difficulty: "easy", tags: ["BJT"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-203", subject: "electronics", chapter: "集成运算放大器", type: "fill",
    stem: "理想运放工作在闭环状态时，两输入端电位近似相等，称为____。", options: undefined,
    answer: "虚短", analysis: "深度负反馈下 u+ ≈ u-。", difficulty: "easy", tags: ["运放"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-204", subject: "electronics", chapter: "组合逻辑电路", type: "fill",
    stem: "逻辑函数 Y = A·B 的与非实现为 Y = (A·B)′，其中′表示____运算。", options: undefined,
    answer: "非", analysis: "与非门 = 与 + 非。", difficulty: "easy", tags: ["逻辑代数"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-205", subject: "electronics", chapter: "触发器与时序逻辑电路", type: "fill",
    stem: "JK 触发器在 J=1、K=1 时，CP 脉冲作用下触发器实现____功能。", options: undefined,
    answer: "翻转", analysis: "J=K=1 时 JK 触发器翻转（计数模式）。", difficulty: "medium", tags: ["触发器"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-206", subject: "electronics", chapter: "直流稳压电源", type: "fill",
    stem: "三端固定输出稳压器 7805 的输出电压为____V。", options: undefined,
    answer: "5", analysis: "78xx 系列：xx 即输出电压，7805 输出 +5V。", difficulty: "easy", tags: ["稳压电源"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-207", subject: "electronics", chapter: "半导体二极管", type: "truefalse",
    stem: "二极管具有单向导电性，反向电压超过击穿电压后二极管一定损坏。", options: ["对", "错"],
    answer: "B", analysis: "稳压管就工作在反向击穿区而不损坏；普通二极管击穿后若限流则可能恢复。", difficulty: "medium", tags: ["二极管"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-208", subject: "electronics", chapter: "反馈放大电路", type: "truefalse",
    stem: "负反馈能减小放大电路的非线性失真。", options: ["对", "错"],
    answer: "A", analysis: "负反馈改善非线性失真（对输入信号内部的失真抑制）。", difficulty: "medium", tags: ["负反馈"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-209", subject: "electronics", chapter: "集成运算放大器", type: "truefalse",
    stem: "运放构成的电压跟随器电压增益约为 1，输出与输入同相。", options: ["对", "错"],
    answer: "A", analysis: "电压跟随器：uo = ui，增益为 1，同相。", difficulty: "easy", tags: ["运放"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-210", subject: "electronics", chapter: "组合逻辑电路", type: "truefalse",
    stem: "编码器的功能是把二进制代码转换为对应的信号。", options: ["对", "错"],
    answer: "B", analysis: "编码器把信号编为二进制代码；译码器才是代码转信号。", difficulty: "easy", tags: ["组合逻辑"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-211", subject: "electronics", chapter: "触发器与时序逻辑电路", type: "truefalse",
    stem: "时序逻辑电路的输出仅取决于当前输入。", options: ["对", "错"],
    answer: "B", analysis: "时序电路输出还取决于电路原状态（有记忆功能）。", difficulty: "easy", tags: ["时序电路"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-212", subject: "electronics", chapter: "功率放大电路", type: "truefalse",
    stem: "乙类功放存在交越失真，甲乙类功放可消除交越失真。", options: ["对", "错"],
    answer: "A", analysis: "乙类在零点附近截止产生交越失真；甲乙类给一点静态偏置消除。", difficulty: "medium", tags: ["功放"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-213", subject: "electronics", chapter: "多级放大电路", type: "truefalse",
    stem: "多级放大电路的总电压增益等于各级增益之和。", options: ["对", "错"],
    answer: "B", analysis: "总增益等于各级增益之积（dB 表示时相加）。", difficulty: "easy", tags: ["多级放大"], source: 'manual', createdAt: '2026-08-01' },
  { id: "elec-214", subject: "electronics", chapter: "脉冲波形的产生与整形", type: "truefalse",
    stem: "555 定时器可以构成施密特触发器、单稳态触发器和多谐振荡器。", options: ["对", "错"],
    answer: "A", analysis: "555 三大典型应用：施密特（整形）、单稳态（定时）、多谐（振荡）。", difficulty: "easy", tags: ["555", "脉冲"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-201", subject: "math", chapter: "函数与极限", type: "fill",
    stem: "lim(x→0) sin x / x = ____。", options: undefined,
    answer: "1", analysis: "第一重要极限。", difficulty: "easy", tags: ["极限"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-202", subject: "math", chapter: "导数与微分", type: "fill",
    stem: "函数 y = x³ 在 x=1 处的导数为____。", options: undefined,
    answer: "3", analysis: "y′ = 3x²，y′(1) = 3。", difficulty: "easy", tags: ["求导"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-203", subject: "math", chapter: "定积分及其应用", type: "fill",
    stem: "∫(0→1) e^x dx = ____。", options: undefined,
    answer: "e-1", analysis: "∫e^x dx = e^x，代入 1、0：e - 1。", difficulty: "easy", tags: ["定积分"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-204", subject: "math", chapter: "无穷级数", type: "fill",
    stem: "幂级数 Σ(x^n/n!)（n 从 0 到 ∞）的和函数为____。", options: undefined,
    answer: "e^x", analysis: "e^x 的麦克劳林展开就是 Σx^n/n!。", difficulty: "medium", tags: ["级数"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-205", subject: "math", chapter: "微分方程", type: "fill",
    stem: "微分方程 y′′ = 0 的通解为 y = ____（C1、C2 为任意常数）。", options: undefined,
    answer: "C1x+C2", analysis: "两次积分：y′ = C1，y = C1x + C2。", difficulty: "medium", tags: ["微分方程"], source: 'manual', createdAt: '2026-08-01' },
  { id: "math-206", subject: "math", chapter: "多元函数微分学", type: "fill",
    stem: "函数 z = x² + y² 在点 (1, 1) 处的偏导数 ∂z/∂x = ____。", options: undefined,
    answer: "2", analysis: "∂z/∂x = 2x，在 (1,1) 处为 2。", difficulty: "easy", tags: ["偏导数"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-201", subject: "politics", chapter: "马克思主义哲学原理", type: "multiple",
    stem: "下列属于唯物辩证法的观点有（多选）：", options: ["世界是普遍联系的", "世界是永恒发展的", "矛盾是事物发展的动力", "静止是绝对的"],
    answer: "ABC", analysis: "辩证法认为联系、发展、矛盾是根本观点；静止是相对的，运动才是绝对的。", difficulty: "medium", tags: ["辩证法"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-202", subject: "politics", chapter: "马克思主义哲学原理", type: "multiple",
    stem: "认识过程的两次飞跃是（多选）：", options: ["从感性认识到理性认识", "从理性认识到实践", "从实践到感性认识", "从现象到本质"],
    answer: "AB", analysis: "认识运动两次飞跃：感性→理性（第一次）、理性→实践（第二次）。", difficulty: "medium", tags: ["认识论"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-203", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "multiple",
    stem: "党的二十大报告指出，中国式现代化是（多选）：", options: ["人口规模巨大的现代化", "全体人民共同富裕的现代化", "物质文明和精神文明相协调的现代化", "走西方化道路的现代化"],
    answer: "ABC", analysis: "中国式现代化五个特征：人口规模巨大、共同富裕、物质文明精神文明协调、人与自然和谐共生、和平发展。", difficulty: "medium", tags: ["中国式现代化"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-204", subject: "politics", chapter: "毛泽东思想及其历史地位", type: "multiple",
    stem: "毛泽东思想活的灵魂包括（多选）：", options: ["实事求是", "群众路线", "独立自主", "武装斗争"],
    answer: "ABC", analysis: "活的灵魂：实事求是、群众路线、独立自主。武装斗争是三大法宝之一。", difficulty: "easy", tags: ["毛概"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-205", subject: "politics", chapter: "新民主主义革命理论", type: "multiple",
    stem: "新民主主义革命的对象是（多选）：", options: ["帝国主义", "封建主义", "官僚资本主义", "民族资产阶级"],
    answer: "ABC", analysis: "三座大山：帝国主义、封建主义、官僚资本主义。民族资产阶级是动摇的同盟者。", difficulty: "easy", tags: ["新民主主义"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-206", subject: "politics", chapter: "社会主义改造理论", type: "multiple",
    stem: "我国社会主义改造中对农业的改造原则包括（多选）：", options: ["自愿互利", "典型示范", "国家帮助", "强制没收"],
    answer: "ABC", analysis: "农业合作化坚持自愿互利、典型示范、国家帮助；强制没收是对官僚资本的政策。", difficulty: "hard", tags: ["社会主义改造"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-207", subject: "politics", chapter: "马克思主义哲学原理", type: "truefalse",
    stem: "辨析：真理是绝对的，因而不存在相对性。", options: ["对", "错"],
    answer: "B", analysis: "真理既有绝对性（内容客观、不可推翻）又有相对性（有条件、需发展），是绝对与相对的统一。", difficulty: "hard", tags: ["真理"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-208", subject: "politics", chapter: "新民主主义革命理论", type: "truefalse",
    stem: "辨析：新民主主义革命是无产阶级领导的社会主义革命。", options: ["对", "错"],
    answer: "B", analysis: "新民主主义革命是资产阶级民主革命性质（反帝反封建），无产阶级领导是其与旧民主主义革命的区别，革命前途是社会主义。", difficulty: "hard", tags: ["新民主主义"], source: 'manual', createdAt: '2026-08-01' },
  { id: "pol-209", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "essay",
    stem: "材料分析：某地推进「百千万工程」促进城乡区域协调发展。结合所学，运用联系与发展的观点分析城乡区域协调发展的必要性。", options: undefined,
    answer: "要点：1.联系普遍性：城乡互为条件相互促进；2.发展不平衡不充分是当前主要矛盾体现；3.协调发展体现整体与部分关系；4.落实举措：要素流动/产业协同/公共服务均等化", analysis: "自评参考：原理（联系/发展）+ 现实（主要矛盾）+ 对策三层展开。", difficulty: "hard", tags: ["材料分析", "协调发展"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-201", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "The number of students in our school ___ (be) about 3000.（用正确形式）", options: undefined,
    answer: "is", analysis: "the number of + 复数名词作主语，谓语用单数。", difficulty: "medium", tags: ["主谓一致"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-202", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "By the time you arrive, I ___ (finish) the work.（用正确时态）", options: undefined,
    answer: "will have finished", analysis: "by the time + 一般现在表将来，主句用将来完成时。", difficulty: "hard", tags: ["时态"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-203", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "The film is worth ___ (see) twice.（用正确形式）", options: undefined,
    answer: "seeing", analysis: "be worth doing：值得做，主动形式表被动意义。", difficulty: "medium", tags: ["非谓语"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-204", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "___ (walk) along the street, I met an old friend.（用正确形式）", options: undefined,
    answer: "walking", analysis: "现在分词作状语，与主语为主动关系，表伴随。", difficulty: "medium", tags: ["非谓语"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-205", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "This is the reason ___ he was late.（用关系词填空）", options: undefined,
    answer: "why", analysis: "先行词 reason 用关系副词 why。", difficulty: "easy", tags: ["定语从句"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-206", subject: "english", chapter: "基本语法规则", type: "fill",
    stem: "He suggested that we ___ (start) early tomorrow.（用正确形式）", options: undefined,
    answer: "start", analysis: "suggest 后接虚拟语气 should do，should 可省略，用动词原形。", difficulty: "medium", tags: ["虚拟语气"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-207", subject: "english", chapter: "阅读理解", type: "single",
    stem: "短文：In recent years, more and more Chinese students choose to study abroad. Some people think it is a good way to broaden their horizons and improve their independence. Others argue that studying at home can also provide quality education without the high cost. Whatever the choice, students should consider their own situation carefully. 问题：What is the passage mainly about?", options: ["The cost of studying abroad", "Different views on studying abroad", "How to choose a university", "The quality of domestic education"],
    answer: "B", analysis: "主旨题：短文并列两种观点（留学好处 vs 国内教育），主要在讨论对留学的不同看法。", difficulty: "medium", tags: ["阅读", "主旨"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-208", subject: "english", chapter: "阅读理解", type: "single",
    stem: "短文：In recent years, more and more Chinese students choose to study abroad. Some people think it is a good way to broaden their horizons and improve their independence. Others argue that studying at home can also provide quality education without the high cost. Whatever the choice, students should consider their own situation carefully. 问题：According to the passage, studying abroad can help students ___.", options: ["save money", "broaden their horizons", "avoid pressure", "get better jobs easily"],
    answer: "B", analysis: "细节题：原文说留学可以 broaden their horizons and improve independence。", difficulty: "easy", tags: ["阅读", "细节"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-209", subject: "english", chapter: "阅读理解", type: "single",
    stem: "短文：In recent years, more and more Chinese students choose to study abroad. Some people think it is a good way to broaden their horizons and improve their independence. Others argue that studying at home can also provide quality education without the high cost. Whatever the choice, students should consider their own situation carefully. 问题：The author suggests that students should ___.", options: ["always study abroad", "never study at home", "consider their own situation", "follow others choice"],
    answer: "C", analysis: "推断题：最后一句 whatever the choice, students should consider their own situation carefully。", difficulty: "medium", tags: ["阅读", "推断"], source: 'manual', createdAt: '2026-08-01' },


  // ===== 2026-08-01 英语完形/信息匹配补题（考试 15+5 题） =====
  { id: "eng-301", subject: "english", chapter: "完形填空", type: "fill",
    stem: "短文：One day, a farmer found an eagle egg and put it under a hen. The eagle grew up with the chickens. It learned to ___ like a chicken. 空格处应填：", options: undefined,
    answer: "cluck", analysis: "cluck（咯咯叫）是鸡的叫声；上下文逻辑：鹰从小和鸡一起长大，学会了像鸡一样叫。", difficulty: "medium", tags: ["完形", "逻辑"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-302", subject: "english", chapter: "完形填空", type: "fill",
    stem: "短文：Many students worry about exams. In fact, a little stress can help us focus, but too much stress is ___ to our health. 空格处应填（bad 的比较级）：", options: undefined,
    answer: "worse", analysis: "too much stress is worse（更糟）；语境对比 a little stress 与 too much stress。", difficulty: "medium", tags: ["完形", "比较级"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-303", subject: "english", chapter: "完形填空", type: "fill",
    stem: "短文：Reading is a good habit. It can not only widen our knowledge ___ also make us think deeply. 空格处应填（固定搭配）：", options: undefined,
    answer: "but", analysis: "not only ... but also：不仅……而且……，固定搭配。", difficulty: "easy", tags: ["完形", "连词"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-304", subject: "english", chapter: "信息匹配", type: "single",
    stem: "信息匹配：左侧标题 1. How to save money; 2. How to stay healthy; 3. How to learn English well。右侧段落：A. You should exercise every day and eat more vegetables. B. Practice speaking and listening every day. C. Write down your expenses and avoid unnecessary shopping. 问：段落 A 匹配哪个标题？", options: ["How to save money", "How to stay healthy", "How to learn English well", "以上都不是"],
    answer: "B", analysis: "段落 A 提到 exercise 和 vegetables，对应健康主题。", difficulty: "easy", tags: ["信息匹配"], source: 'manual', createdAt: '2026-08-01' },
  { id: "eng-305", subject: "english", chapter: "信息匹配", type: "single",
    stem: "信息匹配：左侧标题 1. How to save money; 2. How to stay healthy; 3. How to learn English well。右侧段落：A. You should exercise every day and eat more vegetables. B. Practice speaking and listening every day. C. Write down your expenses and avoid unnecessary shopping. 问：段落 C 匹配哪个标题？", options: ["How to save money", "How to stay healthy", "How to learn English well", "以上都不是"],
    answer: "A", analysis: "段落 C 提到记录开支、避免不必要消费，对应省钱主题。", difficulty: "easy", tags: ["信息匹配"], source: 'manual', createdAt: '2026-08-01' },


  // ===== 2026-08-01 真题录入批（2024 政治 20 + 英语历年 10 + 高数 2024 1 + 电子 2023 1） =====
  { id: "pol-301", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "2023年2月13日至14日在中国北京召开的世界数字教育大会的主题是？", options: ["数字变革与中国未来", "数字变革与教育未来", "数字经济与世界未来", "数字教育与产业发展"],
    answer: "B", analysis: "2024 广东专插本政治真题第 1 题。世界数字教育大会主题：数字变革与教育未来。", difficulty: "easy", tags: ["真题", "2024", "时政"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-302", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "第 19 届亚运会的举办地点是？", options: ["上海", "成都", "杭州", "广州"],
    answer: "C", analysis: "2024 广东专插本政治真题第 2 题。2023 年 9 月第 19 届亚运会在杭州举办。", difficulty: "easy", tags: ["真题", "2024", "时政"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-303", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "2023年12月15日，港珠澳大桥旅游正式向公众开放，举行试运营开通仪式的地点是？", options: ["珠海", "深圳", "香港", "澳门"],
    answer: "A", analysis: "2024 广东专插本政治真题第 3 题。开通仪式在珠海举行。", difficulty: "easy", tags: ["真题", "2024", "时政"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-304", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "中国高铁首次全系统、全要素、全产业链在海外落地的是？", options: ["新马高铁", "雅万高铁", "中老高铁", "中缅高铁"],
    answer: "B", analysis: "2024 广东专插本政治真题第 4 题。雅万高铁（印尼）是中国高铁首次全系统全要素全产业链海外落地。", difficulty: "easy", tags: ["真题", "2024", "时政"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-305", subject: "politics", chapter: "新民主主义革命理论", type: "single",
    stem: "中国革命进入新民主主义革命的标志是？", options: ["辛亥革命", "鸦片战争", "五四运动", "护国运动"],
    answer: "C", analysis: "2024 广东专插本政治真题第 5 题。五四运动是新民主主义革命的开端。", difficulty: "easy", tags: ["真题", "2024", "党史"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-306", subject: "politics", chapter: "毛泽东思想及其历史地位", type: "single",
    stem: "1954年9月，第一届全国人民代表大会制定颁布施行的法律是？", options: ["《中华人民共和国民法典》", "《中华人民共和国宪法》", "《中华人民共和国合同法》", "《中华人民共和国行政法》"],
    answer: "B", analysis: "2024 广东专插本政治真题第 6 题。1954 年第一部宪法诞生。", difficulty: "easy", tags: ["真题", "2024", "毛概"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-307", subject: "politics", chapter: "毛泽东思想及其历史地位", type: "single",
    stem: "标志着党探索中国社会主义建设道路的良好开端的著作是？", options: ["《论十大关系》", "《关于正确处理人民内部矛盾的问题》", "《反对本本主义》", "《人的正确思想是从哪里来的》"],
    answer: "A", analysis: "2024 广东专插本政治真题第 7 题。《论十大关系》(1956) 标志着探索社会主义建设道路的良好开端。", difficulty: "medium", tags: ["真题", "2024", "毛概"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-308", subject: "politics", chapter: "毛泽东思想及其历史地位", type: "single",
    stem: "开启改革开放和社会主义现代化建设新时期的重要会议是？", options: ["党的八大", "党的十一大", "党的十一届三中全会", "党的十二届三中全会"],
    answer: "C", analysis: "2024 广东专插本政治真题第 8 题。1978 年十一届三中全会开启改革开放。", difficulty: "easy", tags: ["真题", "2024", "党史"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-309", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "党的十八大以来，中国特色社会主义进入？", options: ["新世纪", "新阶段", "新时期", "新时代"],
    answer: "D", analysis: "2024 广东专插本政治真题第 9 题。十八大以来进入中国特色社会主义新时代。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-310", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "党执政兴国的第一要务是？", options: ["发展", "革命", "改革", "开放"],
    answer: "A", analysis: "2024 广东专插本政治真题第 10 题。发展是党执政兴国的第一要务。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-311", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "中国特色社会主义最本质的特征是？", options: ["中国共产党领导", "人民代表大会制度", "社会主义市场经济", "以人民为中心"],
    answer: "A", analysis: "2024 广东专插本政治真题第 11 题。最本质特征：中国共产党领导。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-312", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "做好一切工作的价值取向和根本标准是？", options: ["推动经济发展", "促进文化繁荣", "让群众满意", "改善生态环境"],
    answer: "C", analysis: "2024 广东专插本政治真题第 12 题。让群众满意是做好一切工作的价值取向和根本标准。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-313", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "新时代坚持和发展中国特色社会主义的根本动力是？", options: ["实现科技自立自强", "全面深化改革开放", "全面从严治党", "全面建成社会主义现代化国家"],
    answer: "B", analysis: "2024 广东专插本政治真题第 13 题。全面深化改革开放是根本动力。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-314", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "全面建设社会主义现代化国家的首要任务是？", options: ["贯彻新发展理念", "推动高质量发展", "推动高水平对外开放", "推进中国式现代化"],
    answer: "B", analysis: "2024 广东专插本政治真题第 14 题。高质量发展是首要任务。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-315", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "全面依法治国的总抓手是？", options: ["完善中国特色社会主义法律规范体系", "建设中国特色社会主义法治体系", "完善中国特色社会主义法治监督体系", "建设中国特色社会主义法治理论"],
    answer: "B", analysis: "2024 广东专插本政治真题第 15 题。建设中国特色社会主义法治体系是总抓手。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-316", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "社会主义生产的根本目的是？", options: ["推进生产力快速发展", "赢得与资本主义比较优势", "促进科技进步", "增进民生福祉"],
    answer: "D", analysis: "2024 广东专插本政治真题第 16 题。社会主义生产的根本目的是增进民生福祉。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-317", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "在国家安全中，处于首要位置的是？", options: ["政治安全", "经济安全", "军事安全", "社会安全"],
    answer: "A", analysis: "2024 广东专插本政治真题第 17 题。政治安全是国家安全的根本/首要位置。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-318", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "反映军队根本职能和军队建设根本指向的是？", options: ["听党指挥", "能打胜仗", "作风优良", "纪律严明"],
    answer: "B", analysis: "2024 广东专插本政治真题第 18 题。能打胜仗反映军队根本职能和建设根本指向。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-319", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "我国对外工作的出发点和落脚点是？", options: ["维护国家主权、安全、发展利益", "人类命运共同体", "坚持走和平发展道路", "增进人民福祉"],
    answer: "A", analysis: "2024 广东专插本政治真题第 19 题。维护国家主权安全发展利益是外交出发点落脚点。", difficulty: "medium", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "pol-320", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "single",
    stem: "在党的建设中，基础性建设是？", options: ["政治建设", "思想建设", "组织建设", "作风建设"],
    answer: "B", analysis: "2024 广东专插本政治真题第 20 题。思想建设是党的基础性建设。", difficulty: "easy", tags: ["真题", "2024", "习思想"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-401", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "I was in ___ that I forgot to lock the door when I left.", options: ["so a hurry", "such a hurry", "a so hurry", "a such hurry"],
    answer: "B", analysis: "广东专插本英语真题。such + a/an + 名词：such a hurry；so 修饰形容词/副词。", difficulty: "medium", tags: ["真题", "词汇语法"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-402", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "I am worried about my brother. I am not sure ___ he has arrived at the school or not.", options: ["whether", "what", "when", "how"],
    answer: "A", analysis: "广东专插本英语真题。whether ... or not 固定搭配（宾语从句）。", difficulty: "easy", tags: ["真题", "从句"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-403", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "She is old enough ___ on her own.", options: ["live", "to live", "living", "be living"],
    answer: "B", analysis: "广东专插本英语真题。形容词/副词 + enough + to do。", difficulty: "easy", tags: ["真题", "非谓语"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-404", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "He was very excited to read the news ___ Mo Yan had won the Nobel Prize for literature.", options: ["which", "what", "how", "that"],
    answer: "D", analysis: "广东专插本英语真题。news 后为同位语从句，用 that 引导。", difficulty: "medium", tags: ["真题", "从句"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-405", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "I do not have my own room, ___?", options: ["neither does Tom", "neither has Tom", "so does Tom", "so has Tom"],
    answer: "A", analysis: "广东专插本英语真题。否定句后用 neither + 助动词 do 倒装。", difficulty: "medium", tags: ["真题", "倒装"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-406", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "I think you should buy this novel. It is really worth ___.", options: ["reading", "being read", "read", "to read"],
    answer: "A", analysis: "广东专插本英语真题。be worth doing 主动形式表被动。", difficulty: "medium", tags: ["真题", "非谓语"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-407", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "Though the firefighters tried very hard to ___ the fire, it still caused at least five people's death.", options: ["put off", "put out", "put on", "put forward"],
    answer: "B", analysis: "广东专插本英语真题。put out 扑灭（火）；put off 推迟；put on 穿上；put forward 提出。", difficulty: "easy", tags: ["真题", "短语动词"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-408", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "He could hardly tell the differences between the twins because they look ___ each other.", options: ["likely", "unlike", "alike", "like"],
    answer: "C", analysis: "广东专插本英语真题。look alike 看起来相像（alike 表语形容词）。", difficulty: "medium", tags: ["真题", "词汇"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-409", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "By the time you come back, I ___ cleaning the house.", options: ["will finish", "will have finished", "have finished", "will be finishing"],
    answer: "B", analysis: "广东专插本英语真题。by the time + 一般现在时，主句用将来完成时。", difficulty: "medium", tags: ["真题", "时态"], source: 'import', createdAt: '2026-08-01' },
  { id: "eng-410", subject: "english", chapter: "基本语法规则", type: "single",
    stem: "Chinese people spend ___ money on travelling today as they did ten years ago.", options: ["more than twice", "as twice much", "twice as much", "twice more than"],
    answer: "C", analysis: "广东专插本英语真题。twice as much + 不可数名词 + as：倍数 + as much as。", difficulty: "hard", tags: ["真题", "比较级"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-301", subject: "math", chapter: "函数与极限", type: "single",
    stem: "lim(x→0) sin3x / x = ?", options: ["3", "1", "-1", "-3"],
    answer: "A", analysis: "2024 广东专插本高数真题第 1 题。等价无穷小 sin3x ~ 3x，故极限 = 3。", difficulty: "easy", tags: ["真题", "2024", "极限"], source: 'import', createdAt: '2026-08-01' },
  { id: "elec-301", subject: "electronics", chapter: "半导体二极管", type: "single",
    stem: "二极管最主要的特性是？", options: ["正向导通特性", "反向截止特性", "检波特性", "单向导电特性"],
    answer: "D", analysis: "2023 广东专插本电子技术基础真题第 1 题。二极管核心特性是单向导电性。", difficulty: "easy", tags: ["真题", "2023", "二极管"], source: 'import', createdAt: '2026-08-01' },


  // ===== 2026-08-01 真题录入批2（2024 政治多选 + 2022 高数 6 题） =====
  { id: "pol-321", subject: "politics", chapter: "习近平新时代中国特色社会主义思想", type: "multiple",
    stem: "中国空间站全面建成后首次出舱活动、漫步太空的航天员是（多选）：", options: ["费俊龙", "刘洋", "陈冬", "张陆"],
    answer: "AD", analysis: "2024 广东专插本政治真题第 21 题。2023-02-10 神舟十五号乘组首次出舱：费俊龙、张陆。", difficulty: "medium", tags: ["真题", "2024", "时政"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-401", subject: "math", chapter: "函数与极限", type: "single",
    stem: "lim(x→0) (sin3x + sinx) / x = ?", options: ["0", "1", "3", "4"],
    answer: "D", analysis: "2022 广东专插本高数真题第 1 题。等价无穷小：sin3x/x→3，sinx/x→1，和 = 4。", difficulty: "easy", tags: ["真题", "2022", "极限"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-402", subject: "math", chapter: "微分中值定理与导数的应用", type: "single",
    stem: "设函数 f(x) 具有二阶导数，且 f′(0)=-1，f′(1)=0，f″(0)=-1，f″(1)=-3，则下列说法正确的是？", options: ["点 x=0 是函数 f(x) 的极小值点", "点 x=0 是函数 f(x) 的极大值点", "点 x=1 是函数 f(x) 的极小值点", "点 x=1 是函数 f(x) 的极大值点"],
    answer: "D", analysis: "2022 广东专插本高数真题第 2 题。极值必要条件：f′(1)=0 且 f″(1)=-3<0 → x=1 是极大值点；x=0 处 f′(0)≠0 不是极值点。", difficulty: "medium", tags: ["真题", "2022", "极值"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-403", subject: "math", chapter: "不定积分", type: "single",
    stem: "已知 ∫f(x)dx = x² + C，则 ∫x·f(x²)dx = ?", options: ["x⁵ + C", "x⁴ + C", "(1/2)x⁴ + C", "(2/3)x³ + C"],
    answer: "C", analysis: "2022 广东专插本高数真题第 3 题。f(x)=2x，则 x·f(x²)=x·2x²=2x³，∫2x³dx = (1/2)x⁴ + C。", difficulty: "medium", tags: ["真题", "2022", "积分"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-404", subject: "math", chapter: "无穷级数", type: "single",
    stem: "级数 Σ(n=1→∞) (2n-1)/3ⁿ = ?", options: ["2", "1", "3/4", "1/2"],
    answer: "B", analysis: "2022 广东专插本高数真题第 4 题。Σ(2n-1)/3ⁿ = 2Σ(n/3ⁿ) - Σ(1/3ⁿ) = 2·(3/4) - 1/2 = 1。", difficulty: "hard", tags: ["真题", "2022", "级数"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-405", subject: "math", chapter: "定积分及其应用", type: "single",
    stem: "设 D = {(x,y) | 1 ≤ x²+y² ≤ 9}，则 ∬_D 1/(x²+y²) dσ = ?", options: ["2π", "10π", "2πln3", "4πln3"],
    answer: "C", analysis: "2022 广东专插本高数真题第 5 题。极坐标：∫(0→2π)∫(1→3) (1/r²)·r dr dθ = 2π·ln r|(1→3) = 2πln3。", difficulty: "hard", tags: ["真题", "2022", "二重积分"], source: 'import', createdAt: '2026-08-01' },
  { id: "math-406", subject: "math", chapter: "导数与微分", type: "fill",
    stem: "参数方程 x=t²，y=log₃t，则 t=1 处 dy/dx = ____。", options: undefined,
    answer: "1/(2ln3)", analysis: "2022 广东专插本高数真题填空第 6 题。dy/dx = (dy/dt)/(dx/dt) = [1/(t·ln3)]/(2t) = 1/(2t²·ln3)，t=1 时为 1/(2ln3)。", difficulty: "hard", tags: ["真题", "2022", "参数方程"], source: 'import', createdAt: '2026-08-01' },


  // ===== 2026-08-01 真题录入批3（2024 电子技术基础 3 题） =====
  { id: "elec-401", subject: "electronics", chapter: "组合逻辑电路", type: "single",
    stem: "以下哪种不是逻辑函数的表示形式？", options: ["真值表", "表达式", "几何图", "逻辑图"],
    answer: "C", analysis: "2024 广东专插本电子技术基础真题第 17 题。逻辑函数表示形式：真值表、表达式、卡诺图、逻辑图（几何图不是）。", difficulty: "easy", tags: ["真题", "2024", "逻辑代数"], source: 'import', createdAt: '2026-08-01' },
  { id: "elec-402", subject: "electronics", chapter: "直流稳压电源", type: "single",
    stem: "在桥式整流电路中，如果一只整流二极管断开，则该电路？", options: ["引起电源短路", "成为半波整流电路", "仍为桥式整流电路", "引起断路"],
    answer: "B", analysis: "2024 广东专插本电子技术基础真题第 18 题。桥式整流四管中任一管断开 → 只剩半波整流。", difficulty: "medium", tags: ["真题", "2024", "整流"], source: 'import', createdAt: '2026-08-01' },
  { id: "elec-403", subject: "electronics", chapter: "反馈放大电路", type: "fill",
    stem: "改善增益特性用____反馈，相位平衡用____反馈。", options: undefined,
    answer: "负正", analysis: "2024 广东专插本电子技术基础真题填空第 21 题。负反馈改善增益稳定性；正反馈用于振荡器相位平衡。", difficulty: "easy", tags: ["真题", "2024", "反馈"], source: 'import', createdAt: '2026-08-01' },
];
