import { db } from './db';
import type { Question } from './types';

const seedQuestions: Question[] = [
  // 电子技术 - 模电
  { id: 'elec-1', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '在共射放大电路中，输出电压与输入电压的相位关系是？', options: ['同相', '反相', '相差90°', '相差180°'],
    answer: 'B', analysis: '共射放大电路输出与输入反相，这是共射电路的基本特性。共集（射随器）为同相，共基也为同相。',
    difficulty: 'easy', tags: ['BJT', '共射放大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-2', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: 'BJT处于放大区时，发射结和集电结的偏置状态分别是？', options: ['正偏/正偏', '正偏/反偏', '反偏/正偏', '反偏/反偏'],
    answer: 'B', analysis: '放大区：发射结正偏，集电结反偏。饱和区两者都正偏，截止区两者都反偏。',
    difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-3', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放两输入端"虚短"成立的条件是？', options: ['开环', '正反馈', '负反馈深度足够', '电源电压足够大'],
    answer: 'C', analysis: '虚短是负反馈深度足够时的近似。开环时虚短不成立（比较器工作状态）。虚断由输入电阻无穷大保证，任何条件下基本成立。',
    difficulty: 'medium', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-4', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '用卡诺图化简逻辑函数 F(A,B,C,D)=Σm(0,2,5,7,8,10,13,15) 的最简与或式为？', options: ['BD+B\'D\'', 'BD+AC', 'B\'D+BD\'', 'A\'C\'+AC'],
    answer: 'A', analysis: '四变量卡诺图，将最小项填入后圈1合并：m0(0000)、m2(0010)、m8(1000)、m10(1010) → B\'D\'；m5(0101)、m7(0111)、m13(1101)、m15(1111) → BD。',
    difficulty: 'hard', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-28' },

  // 高数
  { id: 'math-1', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (sin 3x) / x = ?', options: ['1', '3', '1/3', '0'],
    answer: 'B', analysis: 'lim(x→0) sin(ax)/x = a。原式 = lim(x→0) (sin 3x)/(3x) × 3 = 1 × 3 = 3。等价无穷小 sin 3x ~ 3x (x→0) 直接得出。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-2', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y = x²·eˣ 的导数 y\' = ?', options: ['2x·eˣ', 'x²·eˣ', 'xeˣ(x+2)', '2xeˣ + eˣ'],
    answer: 'C', analysis: '乘积求导：(uv)\' = u\'v + uv\'。u=x², u\'=2x；v=eˣ, v\'=eˣ。y\'=2xeˣ + x²eˣ = xeˣ(2+x) = xeˣ(x+2)。',
    difficulty: 'easy', tags: ['求导', '乘积法则'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-3', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '∫ x·cos(x²) dx = ?', options: ['sin(x²) + C', '½sin(x²) + C', 'cos(x²) + C', '½cos(x²) + C'],
    answer: 'B', analysis: '凑微分：令 u=x²，du=2xdx，xdx=du/2。∫ xcos(x²)dx = ½∫ cos u du = ½sin u + C = ½sin(x²) + C。',
    difficulty: 'medium', tags: ['积分', '凑微分'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-4', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '曲线 y = x³ - 3x 的拐点坐标是？', options: ['(0, 0)', '(1, -2)', '(-1, 2)', '(0, 0)和(±1, ∓2)'],
    answer: 'A', analysis: 'y\'=3x²-3, y\'\'=6x。令 y\'\'=0 得 x=0。x<0 时 y\'\'<0（凸），x>0 时 y\'\'>0（凹）。拐点为 (0,0)。',
    difficulty: 'medium', tags: ['拐点', '二阶导数'], source: 'manual', createdAt: '2026-07-28' },

  // 英语
  { id: 'eng-1', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I ___ you, I would accept the offer.', options: ['am', 'was', 'were', 'be'],
    answer: 'C', analysis: '虚拟语气，与现在事实相反，if 从句用过去式，be 动词一律用 were。',
    difficulty: 'easy', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-2', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The book ___ on the desk is mine.', options: ['lying', 'laying', 'lied', 'lay'],
    answer: 'A', analysis: 'lie(躺/位于)的现在分词是 lying。lay(放置)是及物动词。后置定语用现在分词。',
    difficulty: 'medium', tags: ['非谓语动词', '分词'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-3', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: 'The word "inevitable" most nearly means:', options: ['avoidable', 'certain to happen', 'impossible', 'desirable'],
    answer: 'B', analysis: 'inevitable = unavoidable, certain to happen（不可避免的，必然发生的）。前缀 in-(不) + evitable(可避免的)。',
    difficulty: 'easy', tags: ['词汇'], source: 'manual', createdAt: '2026-07-28' },

  // 政治
  { id: 'pol-1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '唯物辩证法的实质和核心是？', options: ['质量互变规律', '否定之否定规律', '对立统一规律', '原因和结果'],
    answer: 'C', analysis: '对立统一规律（矛盾规律）揭示了事物发展的源泉和动力，是唯物辩证法的实质和核心。',
    difficulty: 'easy', tags: ['辩证法', '矛盾'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-2', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '中国式现代化的本质要求中，第一位的是？', options: ['实现高质量发展', '坚持中国共产党领导', '发展全过程人民民主', '实现全体人民共同富裕'],
    answer: 'B', analysis: '党的二十大报告明确指出：中国式现代化的本质要求是坚持中国共产党领导，坚持中国特色社会主义。党的领导是第一位的。',
    difficulty: 'easy', tags: ['中国式现代化', '二十大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-3', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'single',
    stem: '毛泽东思想"活的灵魂"不包括以下哪一项？', options: ['实事求是', '群众路线', '独立自主', '武装斗争'],
    answer: 'D', analysis: '毛泽东思想活的灵魂是实事求是、群众路线、独立自主三个方面。武装斗争是"三大法宝"之一（统一战线、武装斗争、党的建设），不是活的灵魂。',
    difficulty: 'medium', tags: ['毛泽东思想', '活的灵魂'], source: 'manual', createdAt: '2026-07-28' },

  // ===== 电子技术补充（模电/数电，真题风格）=====
  { id: 'elec-5', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '共集电极放大电路（射极跟随器）的电压放大倍数约为？', options: ['远大于1', '等于0', '接近1且略小于1', '小于0且绝对值很大'],
    answer: 'C', analysis: '射极跟随器电压增益略小于1，输入电阻大、输出电阻小，常用于缓冲和阻抗变换。',
    difficulty: 'easy', tags: ['BJT', '共集电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-6', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '分压偏置式共射放大电路稳定静态工作点主要依靠？', options: ['增大电源电压', '减小基极电阻Rb', '提高环境温度', 'Re的直流负反馈'],
    answer: 'C', analysis: '发射极电阻Re引入直流负反馈：温度升高→Ic增大→Ie增大→Ue升高→UBE减小→IB减小→Ic回落，从而稳定工作点。',
    difficulty: 'medium', tags: ['BJT', '静态工作点'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-7', subject: 'electronics', chapter: '反馈放大电路', type: 'single',
    stem: '电压串联负反馈对放大电路的影响是？', options: ['稳定输出电流、减小输入电阻', '稳定输出电压、减小输入电阻', '稳定输出电流、增大输入电阻', '稳定输出电压、增大输入电阻'],
    answer: 'D', analysis: '电压负反馈稳定输出电压，串联负反馈增大输入电阻。四种组合：电压/电流×串联/并联，效果各不相同，是高频考点。',
    difficulty: 'medium', tags: ['负反馈'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-8', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放"虚断"成立的依据是？', options: ['开环电压增益无穷大', '输出电阻为零', '通频带无限宽', '输入电阻无穷大'],
    answer: 'D', analysis: '虚断因理想运放输入电阻无穷大，流入输入端电流近似为0。虚短则由开环增益无穷大加负反馈保证。',
    difficulty: 'easy', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-9', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '反相比例运算电路 Rf=100kΩ、R1=10kΩ，电压增益为？', options: ['10', '-11', '11', '-10'],
    answer: 'D', analysis: '反相比例：Av = -Rf/R1 = -100/10 = -10。注意反相放大器增益为负，且可小于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-10', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '同相比例运算电路 Rf=90kΩ、R1=10kΩ，电压增益为？', options: ['9', '10', '-9', '11'],
    answer: 'B', analysis: '同相比例：Av = 1 + Rf/R1 = 1 + 90/10 = 10。同相比例增益恒大于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-11', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '逻辑函数 F=(A·B)\' 用摩根定律展开为？', options: ["A'·B'", "A'+B'", 'A+B', "A·B'"],
    answer: 'B', analysis: '摩根定律：(A·B)\' = A\'+B\'，(A+B)\' = A\'·B\'。与变或、或变与、变量取反，常与卡诺图化简配合考查。',
    difficulty: 'easy', tags: ['摩根定律', '逻辑代数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-12', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '卡诺图中两个相邻最小项合并后可以消去？', options: ['2个变量', '3个变量', '不能消去变量', '1个变量'],
    answer: 'D', analysis: '2^n个相邻最小项合并可消去n个变量。两个相邻格（2¹个）消去1个变量，四个相邻格消去2个变量。',
    difficulty: 'medium', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-13', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'JK触发器在 J=1、K=1 时，CP 到来后触发器的状态为？', options: ['保持原态', '置1', '翻转', '置0'],
    answer: 'C', analysis: 'J=1、K=1 时 JK触发器每来一个CP翻转一次（T触发器功能）。J=K=0保持，J=1、K=0置1，J=0、K=1置0。',
    difficulty: 'medium', tags: ['JK触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-14', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'D触发器在 CP 有效沿到来后，Q 的状态为？', options: ['Q=D', 'Q=Q\'', 'Q=0', 'Q保持不变'],
    answer: 'A', analysis: 'D触发器特性方程 Q(n+1)=D。输出跟随输入，常用于数据寄存和分频。',
    difficulty: 'easy', tags: ['D触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-15', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: '由4个触发器构成的二进制异步计数器最多可有多少种状态？', options: ['8种', '16种', '4种', '32种'],
    answer: 'B', analysis: 'n个触发器构成模2^n计数器。4个触发器最多2^4=16种状态，即模16计数器。',
    difficulty: 'easy', tags: ['计数器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-16', subject: 'electronics', chapter: '直流稳压电源', type: 'single',
    stem: '桥式整流电路（无滤波）输出的直流电压平均值约为副边电压有效值的？', options: ['0.9倍', '0.45倍', '1.2倍', '1.41倍'],
    answer: 'A', analysis: '桥式整流为全波整流，Uo≈0.9U2；半波整流0.45U2；电容滤波后约1.2U2；峰值1.41U2。四个数字是高频考点。',
    difficulty: 'medium', tags: ['整流', '直流电源'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 高数补充 =====
  { id: 'math-5', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (eˣ-1)/x = ?', options: ['1', '0', 'e', '∞'],
    answer: 'A', analysis: '等价无穷小：x→0 时 eˣ-1 ~ x，故原式=1。常用的还有 ln(1+x)~x、1-cos x~x²/2。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-6', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '隐函数 x²+y²=25 在点 (3,4) 处的切线斜率为？', options: ['3/4', '-4/3', '4/3', '-3/4'],
    answer: 'D', analysis: '两边对x求导：2x+2y·y\'=0 → y\'=-x/y。代入(3,4)得 y\'=-3/4。',
    difficulty: 'medium', tags: ['隐函数求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-7', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '定积分 ∫₀¹ x² dx = ?', options: ['1/2', '1/3', '1', '2/3'],
    answer: 'B', analysis: '∫x²dx = x³/3，代入上下限：1/3 - 0 = 1/3。',
    difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-8', subject: 'math', chapter: '定积分及其应用', type: 'single',
    stem: '变上限积分求导：d/dx ∫₀ˣ sin t dt = ?', options: ['sin x', 'cos x', '-cos x', 'x·sin x'],
    answer: 'A', analysis: '微积分基本定理：d/dx ∫ₐˣ f(t)dt = f(x)。代入得 sin x。',
    difficulty: 'easy', tags: ['变上限积分', '求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-9', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '微分方程 y\'+y=0 的通解为？', options: ['y=Ceˣ', 'y=Ce⁻ˣ', 'y=Cx', 'y=C+ln x'],
    answer: 'B', analysis: '一阶线性齐次微分方程，特征方程 r+1=0 → r=-1，通解 y=Ce⁻ˣ。',
    difficulty: 'medium', tags: ['微分方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-10', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: '幂级数 Σ(n=1→∞) xⁿ/n 的收敛半径为？', options: ['1', '0', '∞', '2'],
    answer: 'A', analysis: '比值法：lim|a(n+1)/a(n)| = lim n/(n+1) = 1，收敛半径 R=1/1=1。',
    difficulty: 'medium', tags: ['幂级数', '收敛半径'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-11', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: 'x→0 时，1-cos x 与下列哪个是等价无穷小？', options: ['x²', 'x', 'x³/3', 'x²/2'],
    answer: 'C', analysis: '1-cos x ~ x²/2 (x→0)。由 1-cos x = 2sin²(x/2) 且 sin(x/2)~x/2 推出。',
    difficulty: 'medium', tags: ['等价无穷小', '极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-12', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '设 z=x²y，则 ∂z/∂x = ?', options: ['x²', '2xy', '2x+y', 'xy²'],
    answer: 'B', analysis: '对x求偏导时把y看作常数：∂(x²y)/∂x = 2xy。',
    difficulty: 'easy', tags: ['偏导数', '多元函数'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 英语补充 =====
  { id: 'eng-4', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I had studied harder, I ___ the exam.', options: ['will pass', 'would pass', 'had passed', 'would have passed'],
    answer: 'C', analysis: '与过去事实相反的虚拟语气：if 从句用 had done，主句用 would have done。',
    difficulty: 'medium', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-5', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The number of students in our class ___ 45.', options: ['are', 'is', 'were', 'have been'],
    answer: 'B', analysis: '"the number of + 复数名词"作主语，谓语用单数。"a number of"才是复数谓语。',
    difficulty: 'medium', tags: ['主谓一致'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-6', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He has lived in Beijing ___ 2019.', options: ['since', 'for', 'in', 'at'],
    answer: 'A', analysis: '现在完成时接时间点用 since（since 2019），接时间段用 for（for five years）。',
    difficulty: 'easy', tags: ['时态', '完成时'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-7', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "postpone" 最接近的意思是？', options: ['give up', 'carry on', 'take over', 'put off'],
    answer: 'D', analysis: 'postpone = put off（推迟）。give up放弃、carry on继续、take over接管。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-8', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The man ___ is standing there is our teacher.', options: ['whom', 'who', 'whose', 'which'],
    answer: 'B', analysis: '先行词 the man 在从句中作主语，用 who。whom 作宾语，which 指物，whose 表所有。',
    difficulty: 'easy', tags: ['定语从句'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 政治补充 =====
  { id: 'pol-4', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '"世界的本原是物质"这一观点属于？', options: ['唯心主义一元论', '二元论', '不可知论', '唯物主义一元论'],
    answer: 'D', analysis: '承认世界本原只有一个且是物质，是唯物主义一元论。二元论认为有两个本原，不可知论否认世界可知性。',
    difficulty: 'easy', tags: ['唯物论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-5', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '新民主主义革命的领导阶级是？', options: ['资产阶级', '无产阶级', '农民阶级', '小资产阶级'],
    answer: 'B', analysis: '新民主主义革命是无产阶级领导的。领导权问题是革命成败的关键，这是与旧民主主义革命的根本区别。',
    difficulty: 'easy', tags: ['新民主主义革命'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-6', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '新时代我国社会主要矛盾是？', options: ['人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾', '人民日益增长的物质文化需要同落后的社会生产之间的矛盾', '生产力和生产关系之间的矛盾', '经济基础和上层建筑之间的矛盾'],
    answer: 'A', analysis: '党的十九大提出：新时代主要矛盾是人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。选项B是旧表述。',
    difficulty: 'medium', tags: ['主要矛盾', '新时代'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-7', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '下列不属于"四个自信"的是？', options: ['道路自信', '理论自信', '经济自信', '文化自信'],
    answer: 'C', analysis: '四个自信：道路自信、理论自信、制度自信、文化自信。没有"经济自信"。',
    difficulty: 'easy', tags: ['四个自信'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-8', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '检验认识真理性的唯一标准是？', options: ['逻辑证明', '权威意见', '多数人认同', '实践'],
    answer: 'D', analysis: '实践是检验真理的唯一标准。逻辑证明是重要补充但不是最终标准。',
    difficulty: 'easy', tags: ['认识论'], source: 'manual', createdAt: '2026-07-31' },
];

async function seed() {
  let added = 0;
  for (const q of seedQuestions) {
    const existing = await db.questions.get(q.id);
    if (existing) {
      continue;
    }
    await db.questions.put(q);
    added += 1;
  }
  console.log(added ? `已补充 ${added} 道种子题目` : '题库已是最新，无新增');
}

seed();
