import { db } from './db';
import type { Question } from './types';

const seedQuestions: Question[] = [
  // 电子技术 - 模电
  { id: 'elec-1', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '在共射放大电路中，输出电压与输入电压的相位关系是？', options: ['同相', '反相', '相差90°', '相差180°'],
    answer: 'B', analysis: '共射放大电路输出与输入反相，这是共射电路的基本特性。共集（射随器）为同相，共基也为同相。',
    difficulty: 'easy', tags: ['BJT', '共射放大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-2', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: 'BJT处于放大区时，发射结和集电结的偏置状态分别是？', options: ['正偏/正偏', '正偏/反偏', '反偏/正偏', '反偏/反偏'],
    answer: 'B', analysis: '放大区：发射结正偏，集电结反偏。饱和区两者都正偏，截止区两者都反偏。',
    difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-3', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放两输入端"虚短"成立的条件是？', options: ['开环', '正反馈', '负反馈深度足够', '电源电压足够大'],
    answer: 'C', analysis: '虚短是负反馈深度足够时的近似。开环时虚短不成立（比较器工作状态）。虚断由输入电阻无穷大保证，任何条件下基本成立。',
    difficulty: 'medium', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'elec-4', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '用卡诺图化简逻辑函数 F(A,B,C,D)=Σm(0,2,5,7,8,10,13,15) 的最简与或式为？', options: ['BD+B\'D\'', 'BD+AC', 'B\'D+BD\'', 'A\'C\'+AC'],
    answer: 'A', analysis: '四变量卡诺图，将最小项填入后圈1合并：m0(0000)、m2(0010)、m8(1000)、m10(1010) → B\'D\'；m5(0101)、m7(0111)、m13(1101)、m15(1111) → BD。',
    difficulty: 'hard', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-28' },

  // 高数
  { id: 'math-1', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (sin 3x) / x = ?', options: ['1', '3', '1/3', '0'],
    answer: 'B', analysis: 'lim(x→0) sin(ax)/x = a。原式 = lim(x→0) (sin 3x)/(3x) × 3 = 1 × 3 = 3。等价无穷小 sin 3x ~ 3x (x→0) 直接得出。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-2', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y = x²·eˣ 的导数 y\' = ?', options: ['2x·eˣ', 'x²·eˣ', 'xeˣ(x+2)', '2xeˣ + eˣ'],
    answer: 'C', analysis: '乘积求导：(uv)\' = u\'v + uv\'。u=x², u\'=2x；v=eˣ, v\'=eˣ。y\'=2xeˣ + x²eˣ = xeˣ(2+x) = xeˣ(x+2)。',
    difficulty: 'easy', tags: ['求导', '乘积法则'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-3', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '∫ x·cos(x²) dx = ?', options: ['sin(x²) + C', '½sin(x²) + C', 'cos(x²) + C', '½cos(x²) + C'],
    answer: 'B', analysis: '凑微分：令 u=x²，du=2xdx，xdx=du/2。∫ xcos(x²)dx = ½∫ cos u du = ½sin u + C = ½sin(x²) + C。',
    difficulty: 'medium', tags: ['积分', '凑微分'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'math-4', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '曲线 y = x³ - 3x 的拐点坐标是？', options: ['(0, 0)', '(1, -2)', '(-1, 2)', '(0, 0)和(±1, ∓2)'],
    answer: 'A', analysis: 'y\'=3x²-3, y\'\'=6x。令 y\'\'=0 得 x=0。x<0 时 y\'\'<0（凸），x>0 时 y\'\'>0（凹）。拐点为 (0,0)。',
    difficulty: 'medium', tags: ['拐点', '二阶导数'], source: 'manual', createdAt: '2026-07-28' },

  // 英语
  { id: 'eng-1', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I ___ you, I would accept the offer.', options: ['am', 'was', 'were', 'be'],
    answer: 'C', analysis: '虚拟语气，与现在事实相反，if 从句用过去式，be 动词一律用 were。',
    difficulty: 'easy', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-2', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The book ___ on the desk is mine.', options: ['lying', 'laying', 'lied', 'lay'],
    answer: 'A', analysis: 'lie(躺/位于)的现在分词是 lying。lay(放置)是及物动词。后置定语用现在分词。',
    difficulty: 'medium', tags: ['非谓语动词', '分词'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'eng-3', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: 'The word "inevitable" most nearly means:', options: ['avoidable', 'certain to happen', 'impossible', 'desirable'],
    answer: 'B', analysis: 'inevitable = unavoidable, certain to happen（不可避免的，必然发生的）。前缀 in-(不) + evitable(可避免的)。',
    difficulty: 'easy', tags: ['词汇'], source: 'manual', createdAt: '2026-07-28' },

  // 政治
  { id: 'pol-1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '唯物辩证法的实质和核心是？', options: ['质量互变规律', '否定之否定规律', '对立统一规律', '原因和结果'],
    answer: 'C', analysis: '对立统一规律（矛盾规律）揭示了事物发展的源泉和动力，是唯物辩证法的实质和核心。',
    difficulty: 'easy', tags: ['辩证法', '矛盾'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-2', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '中国式现代化的本质要求中，第一位的是？', options: ['实现高质量发展', '坚持中国共产党领导', '发展全过程人民民主', '实现全体人民共同富裕'],
    answer: 'B', analysis: '党的二十大报告明确指出：中国式现代化的本质要求是坚持中国共产党领导，坚持中国特色社会主义。党的领导是第一位的。',
    difficulty: 'easy', tags: ['中国式现代化', '二十大'], source: 'manual', createdAt: '2026-07-28' },
  { id: 'pol-3', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'single',
    stem: '毛泽东思想"活的灵魂"不包括以下哪一项？', options: ['实事求是', '群众路线', '独立自主', '武装斗争'],
    answer: 'D', analysis: '毛泽东思想活的灵魂是实事求是、群众路线、独立自主三个方面。武装斗争是"三大法宝"之一（统一战线、武装斗争、党的建设），不是活的灵魂。',
    difficulty: 'medium', tags: ['毛泽东思想', '活的灵魂'], source: 'manual', createdAt: '2026-07-28' },

  // ===== 电子技术补充（模电/数电，真题风格）=====
  { id: 'elec-5', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '共集电极放大电路（射极跟随器）的电压放大倍数约为？', options: ['远大于1', '等于0', '接近1且略小于1', '小于0且绝对值很大'],
    answer: 'C', analysis: '射极跟随器电压增益略小于1，输入电阻大、输出电阻小，常用于缓冲和阻抗变换。',
    difficulty: 'easy', tags: ['BJT', '共集电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-6', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '分压偏置式共射放大电路稳定静态工作点主要依靠？', options: ['增大电源电压', '减小基极电阻Rb', '提高环境温度', 'Re的直流负反馈'],
    answer: 'C', analysis: '发射极电阻Re引入直流负反馈：温度升高→Ic增大→Ie增大→Ue升高→UBE减小→IB减小→Ic回落，从而稳定工作点。',
    difficulty: 'medium', tags: ['BJT', '静态工作点'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-7', subject: 'electronics', chapter: '反馈放大电路', type: 'single',
    stem: '电压串联负反馈对放大电路的影响是？', options: ['稳定输出电流、减小输入电阻', '稳定输出电压、减小输入电阻', '稳定输出电流、增大输入电阻', '稳定输出电压、增大输入电阻'],
    answer: 'D', analysis: '电压负反馈稳定输出电压，串联负反馈增大输入电阻。四种组合：电压/电流×串联/并联，效果各不相同，是高频考点。',
    difficulty: 'medium', tags: ['负反馈'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-8', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '理想运放"虚断"成立的依据是？', options: ['开环电压增益无穷大', '输出电阻为零', '通频带无限宽', '输入电阻无穷大'],
    answer: 'D', analysis: '虚断因理想运放输入电阻无穷大，流入输入端电流近似为0。虚短则由开环增益无穷大加负反馈保证。',
    difficulty: 'easy', tags: ['运放', '虚短虚断'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-9', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '反相比例运算电路 Rf=100kΩ、R1=10kΩ，电压增益为？', options: ['10', '-11', '11', '-10'],
    answer: 'D', analysis: '反相比例：Av = -Rf/R1 = -100/10 = -10。注意反相放大器增益为负，且可小于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-10', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '同相比例运算电路 Rf=90kΩ、R1=10kΩ，电压增益为？', options: ['9', '10', '-9', '11'],
    answer: 'B', analysis: '同相比例：Av = 1 + Rf/R1 = 1 + 90/10 = 10。同相比例增益恒大于1。',
    difficulty: 'easy', tags: ['运放', '比例运算'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-11', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '逻辑函数 F=(A·B)\' 用摩根定律展开为？', options: ["A'·B'", "A'+B'", 'A+B', "A·B'"],
    answer: 'B', analysis: '摩根定律：(A·B)\' = A\'+B\'，(A+B)\' = A\'·B\'。与变或、或变与、变量取反，常与卡诺图化简配合考查。',
    difficulty: 'easy', tags: ['摩根定律', '逻辑代数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-12', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '卡诺图中两个相邻最小项合并后可以消去？', options: ['2个变量', '3个变量', '不能消去变量', '1个变量'],
    answer: 'D', analysis: '2^n个相邻最小项合并可消去n个变量。两个相邻格（2¹个）消去1个变量，四个相邻格消去2个变量。',
    difficulty: 'medium', tags: ['卡诺图', '组合逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-13', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'JK触发器在 J=1、K=1 时，CP 到来后触发器的状态为？', options: ['保持原态', '置1', '翻转', '置0'],
    answer: 'C', analysis: 'J=1、K=1 时 JK触发器每来一个CP翻转一次（T触发器功能）。J=K=0保持，J=1、K=0置1，J=0、K=1置0。',
    difficulty: 'medium', tags: ['JK触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-14', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: 'D触发器在 CP 有效沿到来后，Q 的状态为？', options: ['Q=D', 'Q=Q\'', 'Q=0', 'Q保持不变'],
    answer: 'A', analysis: 'D触发器特性方程 Q(n+1)=D。输出跟随输入，常用于数据寄存和分频。',
    difficulty: 'easy', tags: ['D触发器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-15', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: '由4个触发器构成的二进制异步计数器最多可有多少种状态？', options: ['8种', '16种', '4种', '32种'],
    answer: 'B', analysis: 'n个触发器构成模2^n计数器。4个触发器最多2^4=16种状态，即模16计数器。',
    difficulty: 'easy', tags: ['计数器', '时序逻辑'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-16', subject: 'electronics', chapter: '直流稳压电源', type: 'single',
    stem: '桥式整流电路（无滤波）输出的直流电压平均值约为副边电压有效值的？', options: ['0.9倍', '0.45倍', '1.2倍', '1.41倍'],
    answer: 'A', analysis: '桥式整流为全波整流，Uo≈0.9U2；半波整流0.45U2；电容滤波后约1.2U2；峰值1.41U2。四个数字是高频考点。',
    difficulty: 'medium', tags: ['整流', '直流电源'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 高数补充 =====
  { id: 'math-5', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→0) (eˣ-1)/x = ?', options: ['1', '0', 'e', '∞'],
    answer: 'A', analysis: '等价无穷小：x→0 时 eˣ-1 ~ x，故原式=1。常用的还有 ln(1+x)~x、1-cos x~x²/2。',
    difficulty: 'easy', tags: ['极限', '等价无穷小'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-6', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '隐函数 x²+y²=25 在点 (3,4) 处的切线斜率为？', options: ['3/4', '-4/3', '4/3', '-3/4'],
    answer: 'D', analysis: '两边对x求导：2x+2y·y\'=0 → y\'=-x/y。代入(3,4)得 y\'=-3/4。',
    difficulty: 'medium', tags: ['隐函数求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-7', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '定积分 ∫₀¹ x² dx = ?', options: ['1/2', '1/3', '1', '2/3'],
    answer: 'B', analysis: '∫x²dx = x³/3，代入上下限：1/3 - 0 = 1/3。',
    difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-8', subject: 'math', chapter: '定积分及其应用', type: 'single',
    stem: '变上限积分求导：d/dx ∫₀ˣ sin t dt = ?', options: ['sin x', 'cos x', '-cos x', 'x·sin x'],
    answer: 'A', analysis: '微积分基本定理：d/dx ∫ₐˣ f(t)dt = f(x)。代入得 sin x。',
    difficulty: 'easy', tags: ['变上限积分', '求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-9', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '微分方程 y\'+y=0 的通解为？', options: ['y=Ceˣ', 'y=Ce⁻ˣ', 'y=Cx', 'y=C+ln x'],
    answer: 'B', analysis: '一阶线性齐次微分方程，特征方程 r+1=0 → r=-1，通解 y=Ce⁻ˣ。',
    difficulty: 'medium', tags: ['微分方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-10', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: '幂级数 Σ(n=1→∞) xⁿ/n 的收敛半径为？', options: ['1', '0', '∞', '2'],
    answer: 'A', analysis: '比值法：lim|a(n+1)/a(n)| = lim n/(n+1) = 1，收敛半径 R=1/1=1。',
    difficulty: 'medium', tags: ['幂级数', '收敛半径'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-11', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: 'x→0 时，1-cos x 与下列哪个是等价无穷小？', options: ['x²', 'x', 'x³/3', 'x²/2'],
    answer: 'C', analysis: '1-cos x ~ x²/2 (x→0)。由 1-cos x = 2sin²(x/2) 且 sin(x/2)~x/2 推出。',
    difficulty: 'medium', tags: ['等价无穷小', '极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-12', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '设 z=x²y，则 ∂z/∂x = ?', options: ['x²', '2xy', '2x+y', 'xy²'],
    answer: 'B', analysis: '对x求偏导时把y看作常数：∂(x²y)/∂x = 2xy。',
    difficulty: 'easy', tags: ['偏导数', '多元函数'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 英语补充 =====
  { id: 'eng-4', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'If I had studied harder, I ___ the exam.', options: ['will pass', 'would pass', 'had passed', 'would have passed'],
    answer: 'C', analysis: '与过去事实相反的虚拟语气：if 从句用 had done，主句用 would have done。',
    difficulty: 'medium', tags: ['虚拟语气'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-5', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The number of students in our class ___ 45.', options: ['are', 'is', 'were', 'have been'],
    answer: 'B', analysis: '"the number of + 复数名词"作主语，谓语用单数。"a number of"才是复数谓语。',
    difficulty: 'medium', tags: ['主谓一致'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-6', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He has lived in Beijing ___ 2019.', options: ['since', 'for', 'in', 'at'],
    answer: 'A', analysis: '现在完成时接时间点用 since（since 2019），接时间段用 for（for five years）。',
    difficulty: 'easy', tags: ['时态', '完成时'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-7', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "postpone" 最接近的意思是？', options: ['give up', 'carry on', 'take over', 'put off'],
    answer: 'D', analysis: 'postpone = put off（推迟）。give up放弃、carry on继续、take over接管。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-8', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The man ___ is standing there is our teacher.', options: ['whom', 'who', 'whose', 'which'],
    answer: 'B', analysis: '先行词 the man 在从句中作主语，用 who。whom 作宾语，which 指物，whose 表所有。',
    difficulty: 'easy', tags: ['定语从句'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 政治补充 =====
  { id: 'pol-4', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '"世界的本原是物质"这一观点属于？', options: ['唯心主义一元论', '二元论', '不可知论', '唯物主义一元论'],
    answer: 'D', analysis: '承认世界本原只有一个且是物质，是唯物主义一元论。二元论认为有两个本原，不可知论否认世界可知性。',
    difficulty: 'easy', tags: ['唯物论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-5', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '新民主主义革命的领导阶级是？', options: ['资产阶级', '无产阶级', '农民阶级', '小资产阶级'],
    answer: 'B', analysis: '新民主主义革命是无产阶级领导的。领导权问题是革命成败的关键，这是与旧民主主义革命的根本区别。',
    difficulty: 'easy', tags: ['新民主主义革命'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-6', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '新时代我国社会主要矛盾是？', options: ['人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾', '人民日益增长的物质文化需要同落后的社会生产之间的矛盾', '生产力和生产关系之间的矛盾', '经济基础和上层建筑之间的矛盾'],
    answer: 'A', analysis: '党的十九大提出：新时代主要矛盾是人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾。选项B是旧表述。',
    difficulty: 'medium', tags: ['主要矛盾', '新时代'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-7', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '下列不属于"四个自信"的是？', options: ['道路自信', '理论自信', '经济自信', '文化自信'],
    answer: 'C', analysis: '四个自信：道路自信、理论自信、制度自信、文化自信。没有"经济自信"。',
    difficulty: 'easy', tags: ['四个自信'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-8', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '检验认识真理性的唯一标准是？', options: ['逻辑证明', '权威意见', '多数人认同', '实践'],
    answer: 'D', analysis: '实践是检验真理的唯一标准。逻辑证明是重要补充但不是最终标准。',
    difficulty: 'easy', tags: ['认识论'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 电子技术扩充二（elec-17..40，共 24 题）=====
  { id: 'elec-17', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: 'BJT 发射结和集电结都正偏时，三极管工作在？', options: ['放大区', '饱和区', '截止区', '击穿区'],
    answer: 'B', analysis: '两个结都正偏为饱和区；发射结正偏集电结反偏为放大区；两个都反偏为截止区。',
    difficulty: 'easy', tags: ['BJT', '工作状态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-18', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '共射放大电路中增大集电极电阻 Rc，电压增益将？', options: ['减小', '不变', '增大', '变为零'],
    answer: 'C', analysis: '共射增益 Au≈-βRc/rbe，Rc 增大增益增大；但 Rc 过大会使静态工作点进入饱和区。',
    difficulty: 'medium', tags: ['BJT', '共射放大'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-19', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '静态工作点设置过低（IB 偏小）时，输出波形容易出现？', options: ['饱和失真', '交越失真', '截止失真', '电源纹波失真'],
    answer: 'C', analysis: '工作点过低靠近截止区，信号负半周被削顶，产生截止失真；过高则产生饱和失真。',
    difficulty: 'medium', tags: ['BJT', '失真'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-20', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '环境温度升高时，BJT 的集电极电流 Icbo 和 Ic 将？', options: ['减小', '不变', '增大', '先增后减'],
    answer: 'C', analysis: '温度升高→少数载流子增多→Icbo 增大→Ic 增大，这是温漂的主要原因，常用分压偏置抑制。',
    difficulty: 'easy', tags: ['BJT', '温度特性'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-21', subject: 'electronics', chapter: '多级放大电路', type: 'single',
    stem: '能放大直流信号的级间耦合方式是？', options: ['阻容耦合', '变压器耦合', '直接耦合', '光电耦合'],
    answer: 'C', analysis: '阻容耦合和变压器耦合的电容/变压器隔直流，只能传交流；直接耦合可传直流信号，但存在零点漂移问题。',
    difficulty: 'medium', tags: ['多级放大', '耦合'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-22', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'single',
    stem: '射极跟随器（共集电路）的输出电阻特点是？', options: ['很大', '等于Re', '很小', '等于Rc'],
    answer: 'C', analysis: '共集电路输出电阻小、输入电阻大、电压增益≈1，常作缓冲级。',
    difficulty: 'easy', tags: ['共集电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-23', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '差分放大电路的主要作用是抑制？', options: ['差模信号', '共模信号', '高频信号', '低频信号'],
    answer: 'B', analysis: '差分电路利用对称结构抑制共模信号（温漂、电源干扰等），放大差模信号，是运放输入级。',
    difficulty: 'medium', tags: ['差分放大', '运放'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-24', subject: 'electronics', chapter: '功率放大电路', type: 'single',
    stem: '乙类互补对称功率放大器的理想最大效率为？', options: ['50%', '85%', '100%', '78.5%'],
    answer: 'D', analysis: '乙类理想效率 π/4≈78.5%；甲类最大 50%。乙类实际因交越失真需偏置，效率略低于 78.5%。',
    difficulty: 'medium', tags: ['功放', '效率'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-25', subject: 'electronics', chapter: '功率放大电路', type: 'single',
    stem: '乙类互补功放产生交越失真的原因是？', options: ['三极管存在死区电压', '电源电压不足', '负载电阻过小', '信号频率过高'],
    answer: 'A', analysis: '输入信号小于死区电压（约 0.5V）时三极管不导通，输出在过零处出现交越失真，常用甲乙类偏置消除。',
    difficulty: 'medium', tags: ['功放', '交越失真'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-26', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '用运放构成电压比较器时，运放工作在？', options: ['开环状态', '深度负反馈', '正反馈', '深度正反馈'],
    answer: 'A', analysis: '比较器工作在开环（或正反馈滞回）状态，利用开环增益无穷大使输出快速饱和到±Uom。',
    difficulty: 'easy', tags: ['运放', '比较器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-27', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '反相加法电路 R1=R2=Rf=10kΩ，两输入均为 1V 时输出电压为？', options: ['-2V', '2V', '-1V', '0V'],
    answer: 'A', analysis: '反相加法器 Uo=-Rf(U1/R1+U2/R2)=-10×(1/10+1/10)=-2V。',
    difficulty: 'medium', tags: ['运放', '加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-28', subject: 'electronics', chapter: '集成运算放大器', type: 'single',
    stem: '积分运算电路输入方波时，输出波形为？', options: ['三角波', '方波', '正弦波', '矩形波'],
    answer: 'A', analysis: '积分电路对输入求积分：方波积分得三角波；正弦波积分得余弦波。',
    difficulty: 'medium', tags: ['运放', '积分电路'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-29', subject: 'electronics', chapter: '反馈放大电路', type: 'single',
    stem: '电流并联负反馈对放大电路的影响是？', options: ['稳定输出电压、增大输入电阻', '稳定输出电压、减小输入电阻', '稳定输出电流、增大输入电阻', '稳定输出电流、减小输入电阻'],
    answer: 'D', analysis: '电流负反馈稳定输出电流，并联负反馈减小输入电阻。串/并联决定输入电阻增减，电压/电流决定稳定对象。',
    difficulty: 'hard', tags: ['负反馈'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-30', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '十进制数 13 对应的二进制数是？', options: ['1011', '1101', '1110', '1001'],
    answer: 'B', analysis: '13=8+4+1=1101₂。除 2 取余法或按位权展开均可。',
    difficulty: 'easy', tags: ['数制转换'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-31', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '逻辑函数 F=AB+AC 化简后为？', options: ['A(B+C)', 'A+B+C', '(A+B)(A+C)', 'ABC'],
    answer: 'A', analysis: '提取公因子 A：F=A(B+C)。(A+B)(A+C)=A+BC 是另一个常用恒等式，注意区分。',
    difficulty: 'easy', tags: ['逻辑代数', '化简'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-32', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '异或门 F=A⊕B，当 A=1 时 F=？', options: ['B', '1', '0', 'B\''],
    answer: 'D', analysis: 'A=1 时 F=1⊕B=B\'。异或门可作可控反相器：A=0 时 F=B，A=1 时 F=B\'。',
    difficulty: 'easy', tags: ['逻辑门', '异或'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-33', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '半加器与全加器的区别是半加器？', options: ['不考虑低位进位', '考虑低位进位', '输出两个进位', '需要三个输入'],
    answer: 'A', analysis: '半加器只有两个输入（两个本位加数），不考虑低位进位；全加器多一个低位进位输入。',
    difficulty: 'easy', tags: ['加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-34', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '全加器共有几个输入端？', options: ['2个', '4个', '5个', '3个'],
    answer: 'D', analysis: '全加器输入为本位加数 A、B 和低位进位 Ci 共 3 个，输出为本位和 S 和进位 Co。',
    difficulty: 'easy', tags: ['加法器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-35', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '8 线-3 线优先编码器输出为几位二进制代码？', options: ['2位', '4位', '8位', '3位'],
    answer: 'D', analysis: '编码器 n 个输入对应 log2n 位输出：8 输入→3 位（2³=8）。',
    difficulty: 'easy', tags: ['编码器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-36', subject: 'electronics', chapter: '组合逻辑电路', type: 'single',
    stem: '74LS138 属于哪种译码器？', options: ['2线-4线', '4线-16线', '8线-3线', '3线-8线'],
    answer: 'D', analysis: '74LS138 是 3线-8线译码器，常用于构成数据分配器或实现组合逻辑函数。',
    difficulty: 'easy', tags: ['译码器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-37', subject: 'electronics', chapter: '触发器与时序逻辑电路', type: 'single',
    stem: '基本 RS 触发器 R=1、S=0 时，Q 的状态为？', options: ['置1', '置0', '翻转', '保持'],
    answer: 'B', analysis: 'S=1 置1、R=1 置0、S=R=0 保持、S=R=1 为禁止态（输出不确定）。注意 S 对应置位。',
    difficulty: 'easy', tags: ['RS触发器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-38', subject: 'electronics', chapter: '脉冲波形的产生与整形', type: 'single',
    stem: '施密特触发器的主要特点是？', options: ['有滞回特性（回差电压）', '无滞回特性', '只能触发一次', '输出恒为高电平'],
    answer: 'A', analysis: '施密特触发器具有上、下两个阈值电压（回差），能把缓慢变化的信号整形为矩形波，抗干扰能力强。',
    difficulty: 'medium', tags: ['施密特触发器', '波形整形'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-39', subject: 'electronics', chapter: '脉冲波形的产生与整形', type: 'single',
    stem: '555 定时器构成多谐振荡器时，输出波形为？', options: ['方波', '正弦波', '三角波', '锯齿波'],
    answer: 'A', analysis: '多谐振荡器（无稳态）输出矩形波/方波；555 还可构成施密特触发器和单稳态触发器。',
    difficulty: 'medium', tags: ['555定时器'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-40', subject: 'electronics', chapter: '直流稳压电源', type: 'single',
    stem: '桥式整流加电容滤波后，空载输出电压约为副边电压有效值的？', options: ['0.45U2', '0.9U2', '1.2U2', '1.41U2'],
    answer: 'C', analysis: '电容滤波空载时 Uo≈√2U2=1.41U2，带负载后约 1.2U2；纯桥式整流 0.9U2，半波 0.45U2。',
    difficulty: 'medium', tags: ['整流滤波'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 高数扩充二（math-13..30，共 18 题）=====
  { id: 'math-13', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→∞) (1+1/x)ˣ = ?', options: ['1', '∞', 'e', '0'],
    answer: 'C', analysis: '这是第二个重要极限 lim(1+1/x)ˣ=e。第一个重要极限是 lim(sin x/x)=1 (x→0)。',
    difficulty: 'easy', tags: ['重要极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-14', subject: 'math', chapter: '函数与极限', type: 'single',
    stem: '极限 lim(x→2) (x²-4)/(x-2) = ?', options: ['0', '2', '不存在', '4'],
    answer: 'D', analysis: '分子因式分解 (x-2)(x+2)，约去 x-2 得 lim(x+2)=4。这是 0/0 型未定式。',
    difficulty: 'easy', tags: ['极限', '未定式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-15', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '导数定义中，f\'(x₀) 等于？', options: ['lim(h→∞) [f(x₀+h)-f(x₀)]/h', 'lim(h→0) [f(x₀+h)+f(x₀)]/h', 'lim(h→0) [f(x₀+h)-f(x₀)]/h', 'lim(h→0) [f(x₀)-f(x₀+h)]/h'],
    answer: 'C', analysis: '导数是函数增量与自变量增量之比在增量趋于 0 时的极限，几何意义是切线的斜率。',
    difficulty: 'easy', tags: ['导数定义'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-16', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y=sin x 的导数是？', options: ['-cos x', '-sin x', 'tan x', 'cos x'],
    answer: 'D', analysis: '(sin x)\'=cos x，(cos x)\'=-sin x。求导公式要记牢。',
    difficulty: 'easy', tags: ['求导公式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-17', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '函数 y=ln x 的导数是？', options: ['x', 'ln x', '1/ln x', '1/x'],
    answer: 'D', analysis: '(ln x)\'=1/x，(eˣ)\'=eˣ。对数求导公式是高频考点。',
    difficulty: 'easy', tags: ['求导公式'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-18', subject: 'math', chapter: '导数与微分', type: 'single',
    stem: '复合函数 y=(2x+1)³ 的导数 y\' = ?', options: ['3(2x+1)²', '3(2x+1)²·2x', '6(2x+1)', '6(2x+1)²'],
    answer: 'D', analysis: '链式法则：y\'=3(2x+1)²·(2x+1)\'=3(2x+1)²·2=6(2x+1)²。',
    difficulty: 'medium', tags: ['复合函数求导'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-19', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '罗尔定理的三个条件是？', options: ['闭区间连续、开区间可导', '开区间可导、端点值相等', '闭区间连续、开区间可导、端点值相等', '闭区间连续、端点值相等'],
    answer: 'C', analysis: '罗尔定理需要三个条件缺一不可：①闭区间连续 ②开区间可导 ③f(a)=f(b)，结论是存在 ξ 使 f\'(ξ)=0。',
    difficulty: 'medium', tags: ['罗尔定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-20', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '拉格朗日中值定理的结论是？', options: ['存在 ξ 使 f(b)-f(a)=f\'(ξ)(b-a)', '存在 ξ 使 f\'(ξ)=0', 'f(b)=f(a)', '存在 ξ 使 f\'(ξ)=f(ξ)'],
    answer: 'A', analysis: '拉格朗日中值定理：存在 ξ∈(a,b)，使 f(b)-f(a)=f\'(ξ)(b-a)。罗尔定理是它的特例。',
    difficulty: 'medium', tags: ['拉格朗日中值定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-21', subject: 'math', chapter: '微分中值定理与导数的应用', type: 'single',
    stem: '函数 y=x² 在 [1,3] 上满足拉格朗日中值定理的 ξ = ?', options: ['1', '3', '4', '2'],
    answer: 'D', analysis: 'f\'(x)=2x，f(3)-f(1)=9-1=8=2ξ·(3-1)=4ξ，得 ξ=2。',
    difficulty: 'medium', tags: ['拉格朗日中值定理'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-22', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '不定积分 ∫(2x+3)dx = ?', options: ['2x²+3x+C', 'x²+3+C', 'x²+3x+C', '2x+3x+C'],
    answer: 'C', analysis: '∫2x dx=x²，∫3dx=3x，加任意常数 C。逐项积分再合并。',
    difficulty: 'easy', tags: ['不定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-23', subject: 'math', chapter: '定积分', type: 'single',
    stem: '定积分 ∫₀^π sin x dx = ?', options: ['1', '0', '2', '-2'],
    answer: 'C', analysis: '∫sin x dx=-cos x，代入上下限：-cos π-(-cos 0)=1+1=2。',
    difficulty: 'easy', tags: ['定积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-24', subject: 'math', chapter: '不定积分', type: 'single',
    stem: '用分部积分法计算 ∫x·eˣ dx = ?', options: ['eˣ(x+1)+C', 'x²eˣ/2+C', 'eˣ(x²-1)+C', 'eˣ(x-1)+C'],
    answer: 'D', analysis: '分部积分：∫x·eˣdx=x·eˣ-∫eˣdx=eˣ(x-1)+C。选 u=x、dv=eˣdx。',
    difficulty: 'hard', tags: ['分部积分'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-25', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '微分方程 y\'=2x 的通解为？', options: ['y=x²+C', 'y=2x+C', 'y=x²+2x+C', 'y=2x²+C'],
    answer: 'A', analysis: '两边直接积分：y=∫2x dx=x²+C。',
    difficulty: 'easy', tags: ['微分方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-26', subject: 'math', chapter: '微分方程', type: 'single',
    stem: '二阶齐次微分方程 y\'\'-y=0 的通解为？', options: ['y=C₁cos x+C₂sin x', 'y=C₁eˣ+C₂x', 'y=C₁+C₂x', 'y=C₁eˣ+C₂e⁻ˣ'],
    answer: 'D', analysis: '特征方程 r²-1=0，r=±1，通解 y=C₁eˣ+C₂e⁻ˣ。特征根为两个不等实根。',
    difficulty: 'hard', tags: ['微分方程', '特征方程'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-27', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: 'p-级数 Σ(1/n²) 的敛散性是？', options: ['发散', '收敛', '条件收敛', '无法判断'],
    answer: 'B', analysis: 'p-级数 Σ1/nᵖ：p>1 收敛，p≤1 发散。p=2>1，故收敛（且绝对收敛）。',
    difficulty: 'medium', tags: ['p级数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-28', subject: 'math', chapter: '无穷级数', type: 'single',
    stem: '交错级数 Σ(-1)ⁿ/n 的敛散性是？', options: ['绝对收敛', '发散', '条件收敛', '无法判断'],
    answer: 'C', analysis: 'Σ|(-1)ⁿ/n|=Σ1/n 发散，但交错级数本身满足莱布尼茨判别法收敛，故为条件收敛。',
    difficulty: 'hard', tags: ['交错级数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-29', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '设 z=eˣʸ，则 ∂z/∂y = ?', options: ['x·eˣʸ', 'y·eˣʸ', 'eˣʸ', 'xy·eˣʸ'],
    answer: 'A', analysis: '对 y 求偏导时 x 视为常数：∂(eˣʸ)/∂y=eˣʸ·(xy)\'ₓ=eˣʸ·x。',
    difficulty: 'medium', tags: ['偏导数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-30', subject: 'math', chapter: '多元函数微分学', type: 'single',
    stem: '函数 z=x²+y² 的全微分 dz = ?', options: ['xdx+ydy', '2xdx+2ydy', '2x+2y', 'x²dx+y²dy'],
    answer: 'B', analysis: 'dz=(∂z/∂x)dx+(∂z/∂y)dy=2xdx+2ydy。全微分是偏导数与微分的线性组合。',
    difficulty: 'medium', tags: ['全微分'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 英语扩充二（english-9..25，共 17 题）=====
  { id: 'english-9', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'She ___ English since 2020.', options: ['studied', 'was studying', 'has been studying', 'studies'],
    answer: 'C', analysis: 'since+时间点用现在完成进行时 have/has been doing，强调动作持续进行。',
    difficulty: 'medium', tags: ['时态', '完成进行时'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-10', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The bridge ___ in 1990.', options: ['built', 'is built', 'was built', 'builds'],
    answer: 'C', analysis: '桥是被建造的，用被动语态 was built，且 1990 是过去时间。',
    difficulty: 'easy', tags: ['被动语态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-11', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The more you read, ___ you will understand.', options: ['the best', 'better', 'best', 'the better'],
    answer: 'D', analysis: '"the+比较级...，the+比较级..."结构：越...就越...。',
    difficulty: 'medium', tags: ['比较级'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-12', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He must ___ the train; he left home at 7 and it leaves at 7:30.', options: ['miss', 'be missing', 'missed', 'have missed'],
    answer: 'D', analysis: 'must have done 表示对过去情况的肯定推测：他一定错过了火车。',
    difficulty: 'hard', tags: ['情态动词', '推测'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-13', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: '___ is good for your health.', options: ['Swim', 'Swimming', 'Swam', 'To swimming'],
    answer: 'B', analysis: '动名词（-ing 形式）作主语表一般性动作。不定式作主语也可，但此处选项只有 A 合适。',
    difficulty: 'easy', tags: ['非谓语动词', '动名词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-14', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'Neither of the two answers ___ correct.', options: ['are', 'were', 'have been', 'is'],
    answer: 'D', analysis: 'neither of + 复数名词作主语，谓语用单数（neither 表示"两者都不"）。',
    difficulty: 'medium', tags: ['主谓一致'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-15', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: '___ it was raining, we went out.', options: ['Although', 'Because', 'So', 'Unless'],
    answer: 'A', analysis: 'although 引导让步状语从句：尽管下雨，我们还是出去了。',
    difficulty: 'easy', tags: ['连词', '让步状语'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-16', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'She is good ___ playing the piano.', options: ['in', 'on', 'for', 'at'],
    answer: 'D', analysis: 'be good at 擅长...。固定搭配要记牢。',
    difficulty: 'easy', tags: ['介词搭配'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-17', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "abandon" 最接近的意思是？', options: ['give up', 'keep up', 'turn up', 'pick up'],
    answer: 'A', analysis: 'abandon = give up（放弃、抛弃）。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-18', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "acquire" 最接近的意思是？', options: ['lose', 'obtain', 'avoid', 'require'],
    answer: 'B', analysis: 'acquire = obtain（获得、习得）。acquire knowledge 获取知识。',
    difficulty: 'medium', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-19', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "efficient" 的意思是？', options: ['高效的', '充足的', '有效的（正确但不贴切）', '昂贵的'],
    answer: 'A', analysis: 'efficient 高效的（以最少浪费达到目的）；effective 有效的（达到预期效果），两词常混考。',
    difficulty: 'medium', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-20', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "significant" 最接近的意思是？', options: ['次要的', '明显的', '重要的', '普遍的'],
    answer: 'C', analysis: 'significant = important（重要的、显著的）。',
    difficulty: 'easy', tags: ['词汇', '近义词'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-21', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "schedule" 的意思是？', options: ['奖学金', '学期', '评分', '时间表、日程'],
    answer: 'D', analysis: 'schedule 时间表、日程安排。on schedule 按计划，ahead of schedule 提前。',
    difficulty: 'easy', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-22', subject: 'english', chapter: '词汇3000词', type: 'single',
    stem: '单词 "approach" 的意思是？', options: ['责备', '方法、接近', '加速', '撤退'],
    answer: 'B', analysis: 'approach 作名词"方法"（a new approach to the problem），作动词"接近"。',
    difficulty: 'medium', tags: ['词汇'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-23', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He is a student, ___?', options: ['is he', 'does he', 'isn\'t he', 'doesn\'t he'],
    answer: 'C', analysis: '反义疑问句：前肯后否。is a student 是肯定句，疑问尾用 isn\'t he。',
    difficulty: 'easy', tags: ['反义疑问句'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-24', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'He was ___ tired ___ he fell asleep at once.', options: ['so; that', 'such; that', 'too; to', 'very; that'],
    answer: 'A', analysis: 'so...that 如此...以至于（接从句）。such...that 修饰名词，too...to 表"太...而不能"。',
    difficulty: 'medium', tags: ['结果状语从句'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'english-25', subject: 'english', chapter: '基本语法规则', type: 'single',
    stem: 'The work ___ by the end of this month.', options: ['will have been finished', 'will have finished', 'will be finishing', 'finishes'],
    answer: 'A', analysis: 'by+将来时间点用将来完成时；工作是被完成的，故用将来完成被动 will have been finished。',
    difficulty: 'hard', tags: ['时态', '被动语态'], source: 'manual', createdAt: '2026-07-31' },

  // ===== 政治扩充二（politics-9..25，共 17 题）=====
  { id: 'politics-9', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '量变是质变的必要准备，质变是量变的必然结果，这一规律是？', options: ['对立统一规律', '质量互变规律', '否定之否定规律', '价值规律'],
    answer: 'B', analysis: '质量互变规律揭示了事物发展的状态和形式：量变→质变→新的量变。',
    difficulty: 'easy', tags: ['辩证法', '质量互变'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-10', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '实践的基本形式不包括？', options: ['物质生产实践', '社会政治实践', '科学文化实践', '个人消费实践'],
    answer: 'D', analysis: '实践的三种基本形式：物质生产实践（基础）、社会政治实践、科学文化实践。个人消费不属于基本形式。',
    difficulty: 'medium', tags: ['实践', '认识论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-11', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '真理的客观性是指？', options: ['真理的形式是客观的', '真理是多数人认同的', '真理是永恒不变的', '真理的内容是客观的'],
    answer: 'D', analysis: '真理客观性：内容来自客观世界，不依人的意志为转移。真理的形式（判断、概念）是主观的。',
    difficulty: 'medium', tags: ['真理观'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-12', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '新民主主义革命的三大法宝是？', options: ['实事求是、群众路线、独立自主', '武装斗争、土地革命、根据地建设', '统一战线、武装斗争、党的建设', '统一战线、土地革命、党的建设'],
    answer: 'C', analysis: '三大法宝：统一战线、武装斗争、党的建设。注意与"活的灵魂"（实事求是、群众路线、独立自主）区分。',
    difficulty: 'easy', tags: ['新民主主义革命', '三大法宝'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-13', subject: 'politics', chapter: '毛泽东思想及其历史地位', type: 'single',
    stem: '毛泽东思想的精髓是？', options: ['群众路线', '实事求是', '独立自主', '武装斗争'],
    answer: 'B', analysis: '实事求是是毛泽东思想的精髓，也是党的思想路线的核心。',
    difficulty: 'easy', tags: ['毛泽东思想'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-14', subject: 'politics', chapter: '新民主主义革命理论', type: 'single',
    stem: '1949 年新中国成立后到 1956 年，我国社会的主要矛盾是？', options: ['无产阶级与资产阶级的矛盾', '人民日益增长的物质文化需要同落后的社会生产之间的矛盾', '人民对于建立先进的工业国的要求同落后的农业国的现实之间的矛盾', '生产力和生产关系之间的矛盾'],
    answer: 'C', analysis: '过渡时期主要矛盾：人民对于建立先进的工业国的要求同落后的农业国的现实之间的矛盾，即社会主义道路与资本主义道路的矛盾。',
    difficulty: 'hard', tags: ['过渡时期', '主要矛盾'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-15', subject: 'politics', chapter: '社会主义改造理论', type: 'single',
    stem: '社会主义改造基本完成的标志是？', options: ['1954 年宪法颁布', '1956 年三大改造基本完成', '1952 年土改完成', '1958 年人民公社化'],
    answer: 'B', analysis: '1956 年底对农业、手工业、资本主义工商业的社会主义改造基本完成，社会主义基本制度确立。',
    difficulty: 'medium', tags: ['社会主义改造'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-16', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"两个一百年"奋斗目标中，第一个百年目标指？', options: ['基本实现现代化', '全面建成小康社会', '建成社会主义现代化强国', '实现共同富裕'],
    answer: 'B', analysis: '第一个百年（建党 100 年，2021 年）：全面建成小康社会，已如期完成；第二个百年（建国 100 年，2049 年）：建成社会主义现代化强国。',
    difficulty: 'easy', tags: ['两个一百年'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-17', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '新发展理念的内容是？', options: ['创新、协调、绿色、开放、共享', '改革、发展、稳定、创新、协调', '创新、协调、绿色、改革、开放', '发展、协调、绿色、开放、共赢'],
    answer: 'A', analysis: '新发展理念：创新（第一动力）、协调（内生特点）、绿色（普遍形态）、开放（必由之路）、共享（本质要求）。',
    difficulty: 'easy', tags: ['新发展理念'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-18', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"五位一体"总体布局是？', options: ['经济建设、政治建设、文化建设、国防建设、党的建设', '工业化、信息化、城镇化、农业现代化、绿色化', '道路自信、理论自信、制度自信、文化自信、生态自信', '经济建设、政治建设、文化建设、社会建设、生态文明建设'],
    answer: 'D', analysis: '五位一体：经济、政治、文化、社会、生态文明建设。注意与"四个全面"（全面建成小康社会、全面深化改革、全面依法治国、全面从严治党）区分。',
    difficulty: 'medium', tags: ['五位一体'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-19', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '全面深化改革的总目标是？', options: ['完善和发展中国特色社会主义制度，推进国家治理体系和治理能力现代化', '全面建成小康社会', '建设社会主义现代化强国', '实现中华民族伟大复兴'],
    answer: 'A', analysis: '全面深化改革总目标：完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化。',
    difficulty: 'medium', tags: ['全面深化改革'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-20', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '乡村振兴战略的总要求是？', options: ['产业兴旺、生态宜居、乡风文明、治理有效、生活富裕', '生产发展、生活宽裕、乡风文明、村容整洁、管理民主', '产业兴旺、生态宜居、乡风文明、治理有效、共同富裕', '农业强、农村美、农民富'],
    answer: 'A', analysis: '乡村振兴二十字总要求：产业兴旺、生态宜居、乡风文明、治理有效、生活富裕。选项 B 是新农村建设旧提法。',
    difficulty: 'medium', tags: ['乡村振兴'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-21', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '总体国家安全观的宗旨是？', options: ['人民安全', '政治安全', '经济安全', '军事安全'],
    answer: 'A', analysis: '总体国家安全观以人民安全为宗旨、以政治安全为根本、以经济安全为基础。',
    difficulty: 'medium', tags: ['国家安全'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-22', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '2025 年《政府工作报告》提出的国内生产总值增长预期目标是？', options: ['4%左右', '4.5%左右', '5%左右', '5.5%左右'],
    answer: 'C', analysis: '2025 年政府工作报告提出 GDP 增长预期目标 5% 左右，与 2024 年持平。',
    difficulty: 'medium', tags: ['时政', '2025'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-23', subject: 'politics', chapter: '习近平新时代中国特色社会主义思想', type: 'single',
    stem: '"十五五"规划的时间范围是？', options: ['2021-2025年', '2025-2030年', '2026-2030年', '2030-2035年'],
    answer: 'C', analysis: '"十五五"规划即第十五个五年规划，覆盖 2026-2030 年，2025 年 10 月党的二十届四中全会通过建议。',
    difficulty: 'hard', tags: ['时政', '十五五'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-24', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '人类社会发展的基本规律是？', options: ['生产关系一定要适合生产力状况的规律', '上层建筑一定要适合经济基础状况的规律', '价值规律', '剩余价值规律'],
    answer: 'A', analysis: '人类社会两大基本规律：生产关系一定要适合生产力状况、上层建筑一定要适合经济基础状况。A 是最基本的。',
    difficulty: 'medium', tags: ['唯物史观'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'politics-25', subject: 'politics', chapter: '马克思主义哲学原理', type: 'single',
    stem: '唯物辩证法认为事物发展的源泉和动力是？', options: ['内部矛盾', '外部矛盾', '外力推动', '量的积累'],
    answer: 'A', analysis: '内因（内部矛盾）是事物发展的源泉和根本动力，外因通过内因起作用。',
    difficulty: 'easy', tags: ['辩证法', '矛盾'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 多选 / 判断 / 填空 题型补充（电子技术） ======
  { id: 'elec-m1', subject: 'electronics', chapter: '双极结型三极管(BJT)及其放大电路', type: 'multiple',
    stem: '下列哪些电路组态具有电压放大能力？（多选）', options: ['共射', '共集', '共基', '共源'],
    answer: 'AC', analysis: '共射和共基具有电压放大能力；共集（射随器）电压增益≈1，主要做阻抗变换。',
    difficulty: 'medium', tags: ['BJT', '组态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-m2', subject: 'electronics', chapter: '集成运算放大器', type: 'multiple',
    stem: '理想运放的主要特点包括？（多选）', options: ['开环增益无穷大', '输入电阻无穷大', '输出电阻为零', '带宽有限'],
    answer: 'ABC', analysis: '理想运放：开环增益、输入电阻无穷大，输出电阻为零，带宽无穷大。',
    difficulty: 'easy', tags: ['运放'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-t1', subject: 'electronics', chapter: '半导体二极管', type: 'truefalse',
    stem: '硅二极管正向导通时，管压降近似为0.7V。', answer: '对',
    analysis: '硅管正向导通压降约0.6-0.7V，锗管约0.2-0.3V。',
    difficulty: 'easy', tags: ['二极管'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-t2', subject: 'electronics', chapter: '组合逻辑电路', type: 'truefalse',
    stem: '异或门的输出在输入相同时为1。', answer: '错',
    analysis: '异或门：输入相同时输出0，输入不同时输出1。',
    difficulty: 'easy', tags: ['逻辑门'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'elec-f1', subject: 'electronics', chapter: '集成运算放大器', type: 'fill',
    stem: '理想运放两输入端电位近似相等的现象称为____（两个字）。', answer: '虚短',
    analysis: '虚短：负反馈深度足够时两输入端电位近似相等；虚断：输入电流近似为0。',
    difficulty: 'easy', tags: ['运放'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 多选 / 判断 / 填空 题型补充（高数） ======
  { id: 'math-m1', subject: 'math', chapter: '函数与极限', type: 'multiple',
    stem: '下列极限值为1的有？（多选）', options: ['lim(x→0) sinx/x', 'lim(x→∞) (1+1/x)^x', 'lim(x→0) x·sin(1/x)', 'lim(x→0) (e^x-1)/x'],
    answer: 'ABD', analysis: '第一个重要极限、e的定义、等价无穷小均为1；x·sin(1/x) 极限为0（无穷小乘有界量）。',
    difficulty: 'medium', tags: ['极限'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-t1', subject: 'math', chapter: '导数与微分', type: 'truefalse',
    stem: '可导必连续，连续不一定可导。', answer: '对',
    analysis: '可导是连续的充分条件；如 |x| 在 x=0 处连续但不可导。',
    difficulty: 'easy', tags: ['导数'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'math-f1', subject: 'math', chapter: '函数与极限', type: 'fill',
    stem: 'lim(x→0) sin x / x = ____', answer: '1',
    analysis: '第一个重要极限，结果为1。',
    difficulty: 'easy', tags: ['极限'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 判断 / 填空 题型补充（英语） ======
  { id: 'eng-t1', subject: 'english', chapter: '基本语法规则', type: 'truefalse',
    stem: '一般现在时中，主语为第三人称单数时动词需加 -s 或 -es。', answer: '对',
    analysis: '第三人称单数一般现在时：动词加 -s/-es，如 he goes。',
    difficulty: 'easy', tags: ['时态'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'eng-f1', subject: 'english', chapter: '基本语法规则', type: 'fill',
    stem: 'He ____ (go) to school every day. 请写出动词的正确形式。', answer: 'goes',
    analysis: '第三人称单数一般现在时，go 加 -es 变 goes。',
    difficulty: 'easy', tags: ['时态'], source: 'manual', createdAt: '2026-07-31' },

  // ====== 判断 / 填空 题型补充（政治） ======
  { id: 'pol-t1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'truefalse',
    stem: '实践是检验真理的唯一标准。', answer: '对',
    analysis: '马克思主义认识论的基本观点：实践是检验真理的唯一标准。',
    difficulty: 'easy', tags: ['认识论'], source: 'manual', createdAt: '2026-07-31' },
  { id: 'pol-f1', subject: 'politics', chapter: '马克思主义哲学原理', type: 'fill',
    stem: '事物发展的根本原因是____（填：内部矛盾/外部矛盾）。', answer: '内部矛盾',
    analysis: '内因是事物发展的根本原因，外因通过内因起作用。',
    difficulty: 'easy', tags: ['辩证法'], source: 'manual', createdAt: '2026-07-31' },
];

async function seed() {
  let added = 0;
  for (const q of seedQuestions) {
    const existing = await db.questions.get(q.id);
    if (existing) {
      continue;
    }
    await db.questions.put(q);
    added += 1;
  }
  console.log(added ? `已补充 ${added} 道种子题目` : '题库已是最新，无新增');
}

seed();
